USE [BAL_VIEWS]
GO

/****** Object:  View [dbo].[BVW_BAL_LOCATION-BSET_CRIME_STATS_CA]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[BVW_BAL_LOCATION-BSET_CRIME_STATS_CA]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as ADDRESS_TYPE_TXTS
,t12.[val] as ADDRESS_NBR_TXTS
,t11.[val] as ADDRESS_TXTS
,t2.[val] as AGENCY_ID_INT
,t3.[val] as CALL_DATE_DTM
,t4.[val] as CITY_TXTS
,t13.[val] as COMMON_LOCATION_TXTS
,t5.[val] as CRIME_ID_INT
,t6.[val] as NARRATIVE_TXTS
,t7.[val] as OFFENSE_DATE_DTM
,t8.[val] as ORIG_CRIMETYPE_NAME_TXTS
,t9.[val] as REPORT_DATE_DTM
,t10.[val] as STATE_TXTS
FROM 
[BAL_LOCATION].dbo.[BSET_CRIME_STATS_CA-ADDRESS_TYPE-TXTS] t1
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_CA-AGENCY_ID-INT]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_CA-CALL_DATE-DTM]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_CA-CITY-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_CA-CRIME_ID-INT]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_CA-NARRATIVE-TXTS]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_CA-OFFENSE_DATE-DTM]  t7 ON  t7.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_CA-ORIG_CRIMETYPE_NAME-TXTS]  t8 ON  t8.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_CA-REPORT_DATE-DTM]  t9 ON  t9.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_CA-STATE-TXTS]  t10 ON  t10.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_CA-ADDRESS-TXTS]  t11 ON  t11.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_CA-ADDRESS_NBR-TXTS]  t12 ON  t12.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_CA-COMMON_LOCATION-TXTS]  t13 ON  t13.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_LOCATION-BSET_CRIME_STATS_DC]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_LOCATION-BSET_CRIME_STATS_DC]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as BUSINESSIMPROVEMENTDISTRICT_TXTS
,t14.[val] as ANC_TXTS
,t21.[val] as BLOCKSITEADDRESS_TXTS
,t20.[val] as CCN_INT
,t24.[val] as CCN_TXTS
,t22.[val] as CITY_TXTS
,t15.[val] as DISTRICT_TXTS
,t2.[val] as HOTSPOT2004NAME_TXTS
,t3.[val] as HOTSPOT2005NAME_TXTS
,t4.[val] as HOTSPOT2006NAME_TXTS
,t5.[val] as LASTMODIFIEDDATE_DTM
,t6.[val] as LATITUDE_FLT
,t7.[val] as LONGITUDE_FLT
,t8.[val] as METHOD_TXTS
,t9.[val] as NARRATIVE_TXTS
,t16.[val] as NEIGHBORHOODCLUSTER_TXTS
,t10.[val] as NID_INT
,t11.[val] as OFFENSE_TXTS
,t17.[val] as PSA_TXTS
,t12.[val] as REPORTDATETIME_DTM
,t13.[val] as SHIFT_TXTS
,t18.[val] as SMD_TXTS
,t23.[val] as STATE_TXTS
,t19.[val] as WARD_TXTS
FROM 
[BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-BUSINESSIMPROVEMENTDISTRICT-TXTS] t1
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-HOTSPOT2004NAME-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-HOTSPOT2005NAME-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-HOTSPOT2006NAME-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-LASTMODIFIEDDATE-DTM]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-LATITUDE-FLT]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-LONGITUDE-FLT]  t7 ON  t7.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-METHOD-TXTS]  t8 ON  t8.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-NARRATIVE-TXTS]  t9 ON  t9.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-NID-INT]  t10 ON  t10.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-OFFENSE-TXTS]  t11 ON  t11.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-REPORTDATETIME-DTM]  t12 ON  t12.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-SHIFT-TXTS]  t13 ON  t13.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-ANC-TXTS]  t14 ON  t14.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-DISTRICT-TXTS]  t15 ON  t15.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-NEIGHBORHOODCLUSTER-TXTS]  t16 ON  t16.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-PSA-TXTS]  t17 ON  t17.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-SMD-TXTS]  t18 ON  t18.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-WARD-TXTS]  t19 ON  t19.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-CCN-INT]  t20 ON  t20.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-BLOCKSITEADDRESS-TXTS]  t21 ON  t21.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-CITY-TXTS]  t22 ON  t22.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-STATE-TXTS]  t23 ON  t23.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_CRIME_STATS_DC-CCN-TXTS]  t24 ON  t24.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_LOCATION-BSET_EMPLOYER]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_LOCATION-BSET_EMPLOYER]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as CITY_TXTS
,t2.[val] as EMPLOYER_TXTS
,t4.[val] as PAYER_TXTS
,t3.[val] as PAYERDESCRIPTION_TXTS
,t5.[val] as STATE_TXTS
,t7.[val] as STREETADDRESS_TXTS
,t6.[val] as ZIP_TXTS
FROM 
[BAL_LOCATION].dbo.[BSET_EMPLOYER-CITY-TXTS] t1
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_EMPLOYER-EMPLOYER-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_EMPLOYER-PAYERDESCRIPTION-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_EMPLOYER-PAYER-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_EMPLOYER-STATE-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_EMPLOYER-ZIP-TXTS]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_EMPLOYER-STREETADDRESS-TXTS]  t7 ON  t7.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_LOCATION-BSET_INSURER_LOCATION]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_LOCATION-BSET_INSURER_LOCATION]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as INSURANCECOMPANY_TXTS
,t3.[val] as ADDRESS1_TXTS
,t7.[val] as ADDRESS2_TXTS
,t4.[val] as CITY_TXTS
,t2.[val] as LOCATIONNAME_TXTS
,t5.[val] as STATE_TXTS
,t6.[val] as ZIP_TXTS
FROM 
[BAL_LOCATION].dbo.[BSET_INSURER_LOCATION-INSURANCECOMPANY-TXTS] t1
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_INSURER_LOCATION-LOCATIONNAME-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_INSURER_LOCATION-ADDRESS1-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_INSURER_LOCATION-CITY-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_INSURER_LOCATION-STATE-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_INSURER_LOCATION-ZIP-TXTS]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_INSURER_LOCATION-ADDRESS2-TXTS]  t7 ON  t7.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_LOCATION-BSET_ZIP_CODE_LOCATION]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_LOCATION-BSET_ZIP_CODE_LOCATION]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as CITY_TXTS
,t5.[val] as COUNTRY_TXTS
,t13.[val] as COUNTY_TXTS
,t7.[val] as DECOMMISIONED_TXTS
,t14.[val] as HOUSINGUNITS_INT
,t15.[val] as INCOME_FLT
,t16.[val] as LANDAREA_FLT
,t10.[val] as LAT_FLT
,t12.[val] as LOCATION_TXTS
,t9.[val] as LOCATIONTEXT_TXTS
,t11.[val] as LONG_FLT
,t19.[val] as MILITARYRESTRICTIONCODES_TXTS
,t17.[val] as POPULATION_INT
,t2.[val] as PREFERRED_TXTS
,t3.[val] as STATE_TXTS
,t8.[val] as TYPE_TXTS
,t18.[val] as WATERAREA_FLT
,t6.[val] as WORLDREGION_TXTS
,t4.[val] as ZIPCODE_TXTS
FROM 
[BAL_LOCATION].dbo.[BSET_ZIP_CODE_LOCATION-CITY-TXTS] t1
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_ZIP_CODE_LOCATION-PREFERRED-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_ZIP_CODE_LOCATION-STATE-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_ZIP_CODE_LOCATION-ZIPCODE-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_ZIP_CODE_LOCATION-COUNTRY-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_ZIP_CODE_LOCATION-WORLDREGION-TXTS]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_ZIP_CODE_LOCATION-DECOMMISIONED-TXTS]  t7 ON  t7.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_ZIP_CODE_LOCATION-TYPE-TXTS]  t8 ON  t8.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_ZIP_CODE_LOCATION-LOCATIONTEXT-TXTS]  t9 ON  t9.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_ZIP_CODE_LOCATION-LAT-FLT]  t10 ON  t10.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_ZIP_CODE_LOCATION-LONG-FLT]  t11 ON  t11.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_ZIP_CODE_LOCATION-LOCATION-TXTS]  t12 ON  t12.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_ZIP_CODE_LOCATION-COUNTY-TXTS]  t13 ON  t13.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_ZIP_CODE_LOCATION-HOUSINGUNITS-INT]  t14 ON  t14.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_ZIP_CODE_LOCATION-INCOME-FLT]  t15 ON  t15.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_ZIP_CODE_LOCATION-LANDAREA-FLT]  t16 ON  t16.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_ZIP_CODE_LOCATION-POPULATION-INT]  t17 ON  t17.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_ZIP_CODE_LOCATION-WATERAREA-FLT]  t18 ON  t18.[key] = t1.[key]
LEFT OUTER JOIN [BAL_LOCATION].dbo.[BSET_ZIP_CODE_LOCATION-MILITARYRESTRICTIONCODES-TXTS]  t19 ON  t19.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_BILL_TYPE_CODE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_BILL_TYPE_CODE]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as DESCRIPTION_TXTS
,t2.[val] as BILLTYPECODE_TXTS
FROM 
[BAL_MEDICAL_CODE_SETS].dbo.[BSET_BILL_TYPE_CODE-DESCRIPTION-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_BILL_TYPE_CODE-BILLTYPECODE-TXTS]  t2 ON  t2.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_BUNDLING_EDIT]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_BUNDLING_EDIT]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as DESCRIPTION_TXTS
,t2.[val] as MODALLOWED_TXTS
,t3.[val] as PRIMARYCODE_TXTS
,t4.[val] as SECONDARYCODE_TXTS
FROM 
[BAL_MEDICAL_CODE_SETS].dbo.[BSET_BUNDLING_EDIT-DESCRIPTION-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_BUNDLING_EDIT-MODALLOWED-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_BUNDLING_EDIT-PRIMARYCODE-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_BUNDLING_EDIT-SECONDARYCODE-TXTS]  t4 ON  t4.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_BUNDLING_EDIT_MUTUAL_EXCLUDE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_BUNDLING_EDIT_MUTUAL_EXCLUDE]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as CODE1_TXTS
,t2.[val] as CODE2_TXTS
FROM 
[BAL_MEDICAL_CODE_SETS].dbo.[BSET_BUNDLING_EDIT_MUTUAL_EXCLUDE-CODE1-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_BUNDLING_EDIT_MUTUAL_EXCLUDE-CODE2-TXTS]  t2 ON  t2.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_DRG]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_DRG]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as DRGCODE_TXTS
,t2.[val] as DRGTITLE_TXTS
,t4.[val] as DRGTYPE_TXTS
,t3.[val] as MEDICALSERVICEGROUP_TXTS
FROM 
[BAL_MEDICAL_CODE_SETS].dbo.[BSET_DRG-DRGCODE-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DRG-DRGTITLE-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DRG-MEDICALSERVICEGROUP-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DRG-DRGTYPE-TXTS]  t4 ON  t4.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_DRUG]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_DRUG]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as BRAND_NAME_TXTS
,t2.[val] as CATEGORY_TXTS
,t7.[val] as DRUG_ID_TXTS
,t3.[val] as GENERIC_PRODUCT_NAME_TXTS
,t4.[val] as GROUP_TXTS
,t5.[val] as NDC_CODE_TXTS
,t6.[val] as ROUTE_TXTS
FROM 
[BAL_MEDICAL_CODE_SETS].dbo.[BSET_DRUG-BRAND_NAME-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DRUG-CATEGORY-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DRUG-GENERIC_PRODUCT_NAME-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DRUG-GROUP-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DRUG-NDC_CODE-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DRUG-ROUTE-TXTS]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DRUG-DRUG_ID-TXTS]  t7 ON  t7.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_DURABLE_MEDICAL_EQUIPMENT]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_DURABLE_MEDICAL_EQUIPMENT]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as AK_FLT
,t2.[val] as AL_FLT
,t3.[val] as AR_FLT
,t4.[val] as AZ_FLT
,t5.[val] as CA_FLT
,t6.[val] as CATG_TXTS
,t7.[val] as CEILING_FLT
,t8.[val] as CO_FLT
,t9.[val] as CT_FLT
,t10.[val] as DC_FLT
,t11.[val] as DE_FLT
,t60.[val] as DESCRIPTION_TXTS
,t12.[val] as FL_FLT
,t13.[val] as FLOOR_FLT
,t14.[val] as GA_FLT
,t15.[val] as HCPCS_TXTS
,t16.[val] as HI_FLT
,t17.[val] as IA_FLT
,t18.[val] as ID_FLT
,t19.[val] as IL_FLT
,t20.[val] as IN_FLT
,t21.[val] as JURIS_TXTS
,t22.[val] as KS_FLT
,t23.[val] as KY_FLT
,t24.[val] as LA_FLT
,t25.[val] as MA_FLT
,t26.[val] as MD_FLT
,t27.[val] as ME_FLT
,t28.[val] as MI_FLT
,t29.[val] as MN_FLT
,t30.[val] as MO_FLT
,t61.[val] as MOD_TXTS
,t62.[val] as MOD2_TXTS
,t31.[val] as MS_FLT
,t32.[val] as MT_FLT
,t33.[val] as NC_FLT
,t34.[val] as ND_FLT
,t35.[val] as NE_FLT
,t36.[val] as NH_FLT
,t37.[val] as NJ_FLT
,t38.[val] as NM_FLT
,t39.[val] as NV_FLT
,t40.[val] as NY_FLT
,t41.[val] as OH_FLT
,t42.[val] as OK_FLT
,t43.[val] as OR_FLT
,t44.[val] as PA_FLT
,t45.[val] as PR_FLT
,t46.[val] as RI_FLT
,t47.[val] as SC_FLT
,t48.[val] as SD_FLT
,t49.[val] as TN_FLT
,t50.[val] as TX_FLT
,t51.[val] as UT_FLT
,t52.[val] as VA_FLT
,t53.[val] as VI_FLT
,t54.[val] as VT_FLT
,t55.[val] as WA_FLT
,t56.[val] as WI_FLT
,t57.[val] as WV_FLT
,t58.[val] as WY_FLT
,t59.[val] as YEAR_INT
FROM 
[BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-AK-FLT] t1
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-AL-FLT]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-AR-FLT]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-AZ-FLT]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-CA-FLT]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-CATG-TXTS]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-CEILING-FLT]  t7 ON  t7.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-CO-FLT]  t8 ON  t8.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-CT-FLT]  t9 ON  t9.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-DC-FLT]  t10 ON  t10.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-DE-FLT]  t11 ON  t11.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-FL-FLT]  t12 ON  t12.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-FLOOR-FLT]  t13 ON  t13.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-GA-FLT]  t14 ON  t14.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-HCPCS-TXTS]  t15 ON  t15.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-HI-FLT]  t16 ON  t16.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-IA-FLT]  t17 ON  t17.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-ID-FLT]  t18 ON  t18.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-IL-FLT]  t19 ON  t19.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-IN-FLT]  t20 ON  t20.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-JURIS-TXTS]  t21 ON  t21.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-KS-FLT]  t22 ON  t22.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-KY-FLT]  t23 ON  t23.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-LA-FLT]  t24 ON  t24.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MA-FLT]  t25 ON  t25.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MD-FLT]  t26 ON  t26.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-ME-FLT]  t27 ON  t27.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MI-FLT]  t28 ON  t28.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MN-FLT]  t29 ON  t29.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MO-FLT]  t30 ON  t30.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MS-FLT]  t31 ON  t31.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MT-FLT]  t32 ON  t32.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-NC-FLT]  t33 ON  t33.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-ND-FLT]  t34 ON  t34.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-NE-FLT]  t35 ON  t35.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-NH-FLT]  t36 ON  t36.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-NJ-FLT]  t37 ON  t37.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-NM-FLT]  t38 ON  t38.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-NV-FLT]  t39 ON  t39.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-NY-FLT]  t40 ON  t40.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-OH-FLT]  t41 ON  t41.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-OK-FLT]  t42 ON  t42.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-OR-FLT]  t43 ON  t43.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-PA-FLT]  t44 ON  t44.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-PR-FLT]  t45 ON  t45.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-RI-FLT]  t46 ON  t46.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-SC-FLT]  t47 ON  t47.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-SD-FLT]  t48 ON  t48.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-TN-FLT]  t49 ON  t49.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-TX-FLT]  t50 ON  t50.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-UT-FLT]  t51 ON  t51.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-VA-FLT]  t52 ON  t52.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-VI-FLT]  t53 ON  t53.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-VT-FLT]  t54 ON  t54.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-WA-FLT]  t55 ON  t55.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-WI-FLT]  t56 ON  t56.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-WV-FLT]  t57 ON  t57.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-WY-FLT]  t58 ON  t58.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-YEAR-INT]  t59 ON  t59.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-DESCRIPTION-TXTS]  t60 ON  t60.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MOD-TXTS]  t61 ON  t61.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MOD2-TXTS]  t62 ON  t62.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_FACILITY]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_FACILITY]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as ZIP_TXTS
,t2.[val] as CITY_TXTS
,t3.[val] as HOSPITAL_ID_TXTS
,t4.[val] as HOSPITAL_NAME_TXTS
,t5.[val] as STATE_TXTS
,t6.[val] as STREET_ADDRESS_TXTS
FROM 
[BAL_MEDICAL_CODE_SETS].dbo.[BSET_FACILITY-ZIP-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_FACILITY-CITY-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_FACILITY-HOSPITAL_ID-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_FACILITY-HOSPITAL_NAME-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_FACILITY-STATE-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_FACILITY-STREET_ADDRESS-TXTS]  t6 ON  t6.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_GPCI]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_GPCI]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as CARRIERNO_TXTS
,t3.[val] as LOCALITY_TXTS
,t2.[val] as LOCALITYNAME_TXTS
,t4.[val] as MALPRACTICEGPCI_FLT
,t5.[val] as PRACTICEGPCI_FLT
,t6.[val] as WORKGPCI_FLT
,t7.[val] as YEAR_INT
FROM 
[BAL_MEDICAL_CODE_SETS].dbo.[BSET_GPCI-CARRIERNO-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_GPCI-LOCALITYNAME-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_GPCI-LOCALITY-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_GPCI-MALPRACTICEGPCI-FLT]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_GPCI-PRACTICEGPCI-FLT]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_GPCI-WORKGPCI-FLT]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_GPCI-YEAR-INT]  t7 ON  t7.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_HOSPITAL_APC]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_HOSPITAL_APC]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as PROCEDURECODE_TXTS
,t9.[val] as APC_TXTS
,t4.[val] as DESCRIPTION_TXTS
,t6.[val] as MINUNADJCOPAY_FLT
,t8.[val] as NATIONALUNADJCOPAY_FLT
,t5.[val] as PAYMENTRATE_FLT
,t7.[val] as RELATIVEWEIGHT_FLT
,t2.[val] as STATUSINDICATOR_TXTS
,t3.[val] as YEAR_INT
FROM 
[BAL_MEDICAL_CODE_SETS].dbo.[BSET_HOSPITAL_APC-PROCEDURECODE-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_HOSPITAL_APC-STATUSINDICATOR-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_HOSPITAL_APC-YEAR-INT]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_HOSPITAL_APC-DESCRIPTION-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_HOSPITAL_APC-PAYMENTRATE-FLT]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_HOSPITAL_APC-MINUNADJCOPAY-FLT]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_HOSPITAL_APC-RELATIVEWEIGHT-FLT]  t7 ON  t7.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_HOSPITAL_APC-NATIONALUNADJCOPAY-FLT]  t8 ON  t8.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_HOSPITAL_APC-APC-TXTS]  t9 ON  t9.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_HOSPITAL_STATUS_CODE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_HOSPITAL_STATUS_CODE]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as HOSPSTATCODE_TXTS
,t2.[val] as HOSPSTATDESC_TXTS
FROM 
[BAL_MEDICAL_CODE_SETS].dbo.[BSET_HOSPITAL_STATUS_CODE-HOSPSTATCODE-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_HOSPITAL_STATUS_CODE-HOSPSTATDESC-TXTS]  t2 ON  t2.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_ICD9_CODE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_ICD9_CODE]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as DIAGCODE_TXTS
,t2.[val] as DIAGDESC_TXTS
FROM 
[BAL_MEDICAL_CODE_SETS].dbo.[BSET_ICD9_CODE-DIAGCODE-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_ICD9_CODE-DIAGDESC-TXTS]  t2 ON  t2.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_LAB_FEE_SCHEDULE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_LAB_FEE_SCHEDULE]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as AK_FLT
,t2.[val] as AL_FLT
,t3.[val] as AR_FLT
,t4.[val] as AZ_FLT
,t5.[val] as CA1_FLT
,t6.[val] as CA2_FLT
,t7.[val] as CO_FLT
,t8.[val] as CT_FLT
,t9.[val] as DC_FLT
,t10.[val] as DE_FLT
,t62.[val] as DESCRIPTION_TXTS
,t11.[val] as FL_FLT
,t12.[val] as FLOOR_FLT
,t13.[val] as GA_FLT
,t14.[val] as HCPC_TXTS
,t15.[val] as HI_FLT
,t16.[val] as IA_FLT
,t17.[val] as ID_FLT
,t18.[val] as IL_FLT
,t19.[val] as IN_FLT
,t20.[val] as KS_FLT
,t21.[val] as KY_FLT
,t22.[val] as LA_FLT
,t23.[val] as LIMIT_FLT
,t24.[val] as MA_FLT
,t25.[val] as MD_FLT
,t26.[val] as ME_FLT
,t27.[val] as MI_FLT
,t28.[val] as MN_FLT
,t29.[val] as MO1_FLT
,t30.[val] as MO2_FLT
,t63.[val] as MODIFIER_TXTS
,t31.[val] as MS_FLT
,t32.[val] as MT_FLT
,t33.[val] as NC_FLT
,t34.[val] as ND_FLT
,t35.[val] as NE_FLT
,t36.[val] as NH_FLT
,t37.[val] as NJ_FLT
,t38.[val] as NM_FLT
,t39.[val] as NV_FLT
,t40.[val] as NY1_FLT
,t41.[val] as NY2_FLT
,t42.[val] as NY3_FLT
,t43.[val] as OH_FLT
,t44.[val] as OK_FLT
,t45.[val] as OR_FLT
,t46.[val] as PA_FLT
,t47.[val] as POINT_FLT
,t48.[val] as PR_FLT
,t49.[val] as RI_FLT
,t50.[val] as SC_FLT
,t51.[val] as SD_FLT
,t52.[val] as TN_FLT
,t53.[val] as TX_FLT
,t54.[val] as UT_FLT
,t55.[val] as VA_FLT
,t56.[val] as VT_FLT
,t57.[val] as WA_FLT
,t58.[val] as WI_FLT
,t59.[val] as WV_FLT
,t60.[val] as WY_FLT
,t61.[val] as YEAR_INT
FROM 
[BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-AK-FLT] t1
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-AL-FLT]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-AR-FLT]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-AZ-FLT]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-CA1-FLT]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-CA2-FLT]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-CO-FLT]  t7 ON  t7.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-CT-FLT]  t8 ON  t8.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-DC-FLT]  t9 ON  t9.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-DE-FLT]  t10 ON  t10.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-FL-FLT]  t11 ON  t11.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-FLOOR-FLT]  t12 ON  t12.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-GA-FLT]  t13 ON  t13.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-HCPC-TXTS]  t14 ON  t14.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-HI-FLT]  t15 ON  t15.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-IA-FLT]  t16 ON  t16.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-ID-FLT]  t17 ON  t17.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-IL-FLT]  t18 ON  t18.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-IN-FLT]  t19 ON  t19.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-KS-FLT]  t20 ON  t20.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-KY-FLT]  t21 ON  t21.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-LA-FLT]  t22 ON  t22.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-LIMIT-FLT]  t23 ON  t23.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-MA-FLT]  t24 ON  t24.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-MD-FLT]  t25 ON  t25.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-ME-FLT]  t26 ON  t26.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-MI-FLT]  t27 ON  t27.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-MN-FLT]  t28 ON  t28.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-MO1-FLT]  t29 ON  t29.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-MO2-FLT]  t30 ON  t30.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-MS-FLT]  t31 ON  t31.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-MT-FLT]  t32 ON  t32.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-NC-FLT]  t33 ON  t33.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-ND-FLT]  t34 ON  t34.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-NE-FLT]  t35 ON  t35.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-NH-FLT]  t36 ON  t36.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-NJ-FLT]  t37 ON  t37.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-NM-FLT]  t38 ON  t38.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-NV-FLT]  t39 ON  t39.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-NY1-FLT]  t40 ON  t40.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-NY2-FLT]  t41 ON  t41.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-NY3-FLT]  t42 ON  t42.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-OH-FLT]  t43 ON  t43.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-OK-FLT]  t44 ON  t44.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-OR-FLT]  t45 ON  t45.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-PA-FLT]  t46 ON  t46.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-POINT-FLT]  t47 ON  t47.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-PR-FLT]  t48 ON  t48.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-RI-FLT]  t49 ON  t49.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-SC-FLT]  t50 ON  t50.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-SD-FLT]  t51 ON  t51.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-TN-FLT]  t52 ON  t52.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-TX-FLT]  t53 ON  t53.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-UT-FLT]  t54 ON  t54.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-VA-FLT]  t55 ON  t55.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-VT-FLT]  t56 ON  t56.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-WA-FLT]  t57 ON  t57.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-WI-FLT]  t58 ON  t58.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-WV-FLT]  t59 ON  t59.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-WY-FLT]  t60 ON  t60.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-YEAR-INT]  t61 ON  t61.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-DESCRIPTION-TXTS]  t62 ON  t62.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_LAB_FEE_SCHEDULE-MODIFIER-TXTS]  t63 ON  t63.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_MODIFIER]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_MODIFIER]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as MODDESC_TXTS
,t2.[val] as MOD_TXTS
FROM 
[BAL_MEDICAL_CODE_SETS].dbo.[BSET_MODIFIER-MODDESC-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_MODIFIER-MOD-TXTS]  t2 ON  t2.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_NPFS]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_NPFS]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as ASSTSURG_TXTS
,t2.[val] as BILATSURG_TXTS
,t3.[val] as COSURG_TXTS
,t4.[val] as CPTCODE_TXTS
,t5.[val] as DESCRIPTION_TXTS
,t20.[val] as ENDOBASE_TXTS
,t6.[val] as FACRVU_FLT
,t15.[val] as GLOBALDAYS_TXTS
,t16.[val] as INTRAOP_FLT
,t19.[val] as MOD_TXTS
,t7.[val] as MPRVU_FLT
,t8.[val] as MULTPROC_TXTS
,t9.[val] as NONFACRVU_FLT
,t10.[val] as PCTC_TXTS
,t17.[val] as POSTOP_FLT
,t18.[val] as PREOP_FLT
,t11.[val] as STATUSCODE_TXTS
,t12.[val] as TEAMSURG_TXTS
,t13.[val] as WORKRVU_FLT
,t14.[val] as YEAR_INT
FROM 
[BAL_MEDICAL_CODE_SETS].dbo.[BSET_NPFS-ASSTSURG-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_NPFS-BILATSURG-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_NPFS-COSURG-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_NPFS-CPTCODE-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_NPFS-DESCRIPTION-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_NPFS-FACRVU-FLT]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_NPFS-MPRVU-FLT]  t7 ON  t7.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_NPFS-MULTPROC-TXTS]  t8 ON  t8.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_NPFS-NONFACRVU-FLT]  t9 ON  t9.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_NPFS-PCTC-TXTS]  t10 ON  t10.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_NPFS-STATUSCODE-TXTS]  t11 ON  t11.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_NPFS-TEAMSURG-TXTS]  t12 ON  t12.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_NPFS-WORKRVU-FLT]  t13 ON  t13.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_NPFS-YEAR-INT]  t14 ON  t14.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_NPFS-GLOBALDAYS-TXTS]  t15 ON  t15.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_NPFS-INTRAOP-FLT]  t16 ON  t16.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_NPFS-POSTOP-FLT]  t17 ON  t17.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_NPFS-PREOP-FLT]  t18 ON  t18.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_NPFS-MOD-TXTS]  t19 ON  t19.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_NPFS-ENDOBASE-TXTS]  t20 ON  t20.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_PCTC]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_PCTC]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as PCTCDESC_TXTS
,t2.[val] as PCTC_TXTS
FROM 
[BAL_MEDICAL_CODE_SETS].dbo.[BSET_PCTC-PCTCDESC-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_PCTC-PCTC-TXTS]  t2 ON  t2.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_PHYSICIAN_STATUS_CODE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_PHYSICIAN_STATUS_CODE]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as STATUSCODEDESC_TXTS
,t2.[val] as STATUSCODE_TXTS
FROM 
[BAL_MEDICAL_CODE_SETS].dbo.[BSET_PHYSICIAN_STATUS_CODE-STATUSCODEDESC-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_PHYSICIAN_STATUS_CODE-STATUSCODE-TXTS]  t2 ON  t2.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_PLACE_OF_SERVICE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_PLACE_OF_SERVICE]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as POSDESC_TXTS
,t2.[val] as POS_TXTS
FROM 
[BAL_MEDICAL_CODE_SETS].dbo.[BSET_PLACE_OF_SERVICE-POSDESC-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_PLACE_OF_SERVICE-POS-TXTS]  t2 ON  t2.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_TAXONOMY_CODE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_TAXONOMY_CODE]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as CLASSIFICATION_TXTS
,t2.[val] as CODE_TXTS
,t7.[val] as DEFINITION_TXTL
,t5.[val] as DEFINITION_TXTS
,t8.[val] as NOTES_TXTL
,t6.[val] as NOTES_TXTS
,t4.[val] as SPECIALIZATION_TXTS
,t3.[val] as TYPE_TXTS
FROM 
[BAL_MEDICAL_CODE_SETS].dbo.[BSET_TAXONOMY_CODE-CLASSIFICATION-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_TAXONOMY_CODE-CODE-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_TAXONOMY_CODE-TYPE-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_TAXONOMY_CODE-SPECIALIZATION-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_TAXONOMY_CODE-DEFINITION-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_TAXONOMY_CODE-NOTES-TXTS]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_TAXONOMY_CODE-DEFINITION-TXTL]  t7 ON  t7.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_TAXONOMY_CODE-NOTES-TXTL]  t8 ON  t8.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_TYPE_OF_SERVICE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_TYPE_OF_SERVICE]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as TOSDESC_TXTS
,t2.[val] as TOS_TXTS
FROM 
[BAL_MEDICAL_CODE_SETS].dbo.[BSET_TYPE_OF_SERVICE-TOSDESC-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_CODE_SETS].dbo.[BSET_TYPE_OF_SERVICE-TOS-TXTS]  t2 ON  t2.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_PROVIDER-BSET_NPI]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_PROVIDER-BSET_NPI]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as ENTITY_TYPE_CODE_TXTS
,t41.[val] as AUTHORIZED_OFFICIAL_CREDENTIAL_TEXT_TXTS
,t31.[val] as AUTHORIZED_OFFICIAL_FIRST_NAME_TXTS
,t36.[val] as AUTHORIZED_OFFICIAL_LAST_NAME_TXTS
,t38.[val] as AUTHORIZED_OFFICIAL_MIDDLE_NAME_TXTS
,t39.[val] as AUTHORIZED_OFFICIAL_NAME_PREFIX_TEXT_TXTS
,t61.[val] as AUTHORIZED_OFFICIAL_NAME_SUFFIX_TEXT_TXTS
,t32.[val] as AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER_TXTS
,t35.[val] as AUTHORIZED_OFFICIAL_TITLE_OR_POSITION_TXTS
,t33.[val] as EMPLOYER_IDENTIFICATION_NUMBER_EIN_TXTS
,t13.[val] as HEALTHCARE_PROVIDER_TAXONOMY_CODE_1_TXTS
,t40.[val] as HEALTHCARE_PROVIDER_TAXONOMY_CODE_2_TXTS
,t50.[val] as HEALTHCARE_PROVIDER_TAXONOMY_CODE_3_TXTS
,t42.[val] as HEALTHCARE_PROVIDER_TAXONOMY_GROUP_1_TXTS
,t58.[val] as HEALTHCARE_PROVIDER_TAXONOMY_GROUP_2_TXTS
,t60.[val] as HEALTHCARE_PROVIDER_TAXONOMY_GROUP_3_TXTS
,t37.[val] as IS_ORGANIZATION_SUBPART_TXTS
,t20.[val] as IS_SOLE_PROPRIETOR_TXTS
,t2.[val] as LAST_UPDATE_DATE_DTM
,t62.[val] as NPI_DEACTIVATION_DATE_DTM
,t3.[val] as NPI_INT
,t63.[val] as NPI_REACTIVATION_DATE_DTM
,t56.[val] as PARENT_ORGANIZATION_LBN_TXTS
,t55.[val] as PARENT_ORGANIZATION_TIN_TXTS
,t4.[val] as PROVIDER_BUSINESS_MAILING_ADDRESS_CITY_NAME_TXTS
,t5.[val] as PROVIDER_BUSINESS_MAILING_ADDRESS_COUNTRY_CODE_IF_OUTSIDE_U_S_TXTS
,t26.[val] as PROVIDER_BUSINESS_MAILING_ADDRESS_FAX_NUMBER_TXTS
,t15.[val] as PROVIDER_BUSINESS_MAILING_ADDRESS_POSTAL_CODE_TXTS
,t6.[val] as PROVIDER_BUSINESS_MAILING_ADDRESS_STATE_NAME_TXTS
,t17.[val] as PROVIDER_BUSINESS_MAILING_ADDRESS_TELEPHONE_NUMBER_TXTS
,t7.[val] as PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME_TXTS
,t8.[val] as PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_COUNTRY_CODE_IF_OUTSIDE_U_S_TXTS
,t25.[val] as PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_FAX_NUMBER_TXTS
,t16.[val] as PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE_TXTS
,t9.[val] as PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME_TXTS
,t14.[val] as PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER_TXTS
,t24.[val] as PROVIDER_CREDENTIAL_TEXT_TXTS
,t10.[val] as PROVIDER_ENUMERATION_DATE_DTM
,t11.[val] as PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS_TXTS
,t12.[val] as PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS_TXTS
,t21.[val] as PROVIDER_FIRST_NAME_TXTS
,t22.[val] as PROVIDER_GENDER_CODE_TXTS
,t23.[val] as PROVIDER_LAST_NAME_LEGAL_NAME_TXTS
,t19.[val] as PROVIDER_LICENSE_NUMBER_1_TXTS
,t44.[val] as PROVIDER_LICENSE_NUMBER_2_TXTS
,t54.[val] as PROVIDER_LICENSE_NUMBER_3_TXTS
,t18.[val] as PROVIDER_LICENSE_NUMBER_STATE_CODE_1_TXTS
,t43.[val] as PROVIDER_LICENSE_NUMBER_STATE_CODE_2_TXTS
,t52.[val] as PROVIDER_LICENSE_NUMBER_STATE_CODE_3_TXTS
,t27.[val] as PROVIDER_MIDDLE_NAME_TXTS
,t28.[val] as PROVIDER_NAME_PREFIX_TEXT_TXTS
,t57.[val] as PROVIDER_NAME_SUFFIX_TEXT_TXTS
,t34.[val] as PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME_TXTS
,t53.[val] as PROVIDER_OTHER_CREDENTIAL_TEXT_TXTS
,t47.[val] as PROVIDER_OTHER_FIRST_NAME_TXTS
,t49.[val] as PROVIDER_OTHER_LAST_NAME_TXTS
,t48.[val] as PROVIDER_OTHER_LAST_NAME_TYPE_CODE_TXTS
,t51.[val] as PROVIDER_OTHER_MIDDLE_NAME_TXTS
,t59.[val] as PROVIDER_OTHER_NAME_PREFIX_TEXT_TXTS
,t64.[val] as PROVIDER_OTHER_NAME_SUFFIX_TEXT_TXTS
,t46.[val] as PROVIDER_OTHER_ORGANIZATION_NAME_TXTS
,t45.[val] as PROVIDER_OTHER_ORGANIZATION_NAME_TYPE_CODE_TXTS
,t30.[val] as PROVIDER_SECOND_LINE_BUSINESS_MAILING_ADDRESS_TXTS
,t29.[val] as PROVIDER_SECOND_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS_TXTS
,t65.[val] as REPLACEMENT_NPI_TXTS
FROM 
[BAL_PROVIDER].dbo.[BSET_NPI-ENTITY_TYPE_CODE-TXTS] t1
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-LAST_UPDATE_DATE-DTM]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-NPI-INT]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_MAILING_ADDRESS_CITY_NAME-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_MAILING_ADDRESS_COUNTRY_CODE_IF_OUTSIDE_U_S-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_MAILING_ADDRESS_STATE_NAME-TXTS]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME-TXTS]  t7 ON  t7.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_COUNTRY_CODE_IF_OUTSIDE_U_S-TXTS]  t8 ON  t8.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME-TXTS]  t9 ON  t9.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_ENUMERATION_DATE-DTM]  t10 ON  t10.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS-TXTS]  t11 ON  t11.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS-TXTS]  t12 ON  t12.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1-TXTS]  t13 ON  t13.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER-TXTS]  t14 ON  t14.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_MAILING_ADDRESS_POSTAL_CODE-TXTS]  t15 ON  t15.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE-TXTS]  t16 ON  t16.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_MAILING_ADDRESS_TELEPHONE_NUMBER-TXTS]  t17 ON  t17.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_LICENSE_NUMBER_STATE_CODE_1-TXTS]  t18 ON  t18.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_LICENSE_NUMBER_1-TXTS]  t19 ON  t19.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-IS_SOLE_PROPRIETOR-TXTS]  t20 ON  t20.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_FIRST_NAME-TXTS]  t21 ON  t21.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_GENDER_CODE-TXTS]  t22 ON  t22.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_LAST_NAME_LEGAL_NAME-TXTS]  t23 ON  t23.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_CREDENTIAL_TEXT-TXTS]  t24 ON  t24.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_FAX_NUMBER-TXTS]  t25 ON  t25.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_MAILING_ADDRESS_FAX_NUMBER-TXTS]  t26 ON  t26.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_MIDDLE_NAME-TXTS]  t27 ON  t27.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_NAME_PREFIX_TEXT-TXTS]  t28 ON  t28.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_SECOND_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS-TXTS]  t29 ON  t29.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_SECOND_LINE_BUSINESS_MAILING_ADDRESS-TXTS]  t30 ON  t30.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-AUTHORIZED_OFFICIAL_FIRST_NAME-TXTS]  t31 ON  t31.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER-TXTS]  t32 ON  t32.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-EMPLOYER_IDENTIFICATION_NUMBER_EIN-TXTS]  t33 ON  t33.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME-TXTS]  t34 ON  t34.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-AUTHORIZED_OFFICIAL_TITLE_OR_POSITION-TXTS]  t35 ON  t35.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-AUTHORIZED_OFFICIAL_LAST_NAME-TXTS]  t36 ON  t36.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-IS_ORGANIZATION_SUBPART-TXTS]  t37 ON  t37.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-AUTHORIZED_OFFICIAL_MIDDLE_NAME-TXTS]  t38 ON  t38.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-AUTHORIZED_OFFICIAL_NAME_PREFIX_TEXT-TXTS]  t39 ON  t39.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_2-TXTS]  t40 ON  t40.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-AUTHORIZED_OFFICIAL_CREDENTIAL_TEXT-TXTS]  t41 ON  t41.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_GROUP_1-TXTS]  t42 ON  t42.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_LICENSE_NUMBER_STATE_CODE_2-TXTS]  t43 ON  t43.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_LICENSE_NUMBER_2-TXTS]  t44 ON  t44.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_OTHER_ORGANIZATION_NAME_TYPE_CODE-TXTS]  t45 ON  t45.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_OTHER_ORGANIZATION_NAME-TXTS]  t46 ON  t46.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_OTHER_FIRST_NAME-TXTS]  t47 ON  t47.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_OTHER_LAST_NAME_TYPE_CODE-TXTS]  t48 ON  t48.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_OTHER_LAST_NAME-TXTS]  t49 ON  t49.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_3-TXTS]  t50 ON  t50.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_OTHER_MIDDLE_NAME-TXTS]  t51 ON  t51.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_LICENSE_NUMBER_STATE_CODE_3-TXTS]  t52 ON  t52.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_OTHER_CREDENTIAL_TEXT-TXTS]  t53 ON  t53.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_LICENSE_NUMBER_3-TXTS]  t54 ON  t54.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PARENT_ORGANIZATION_TIN-TXTS]  t55 ON  t55.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PARENT_ORGANIZATION_LBN-TXTS]  t56 ON  t56.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_NAME_SUFFIX_TEXT-TXTS]  t57 ON  t57.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_GROUP_2-TXTS]  t58 ON  t58.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_OTHER_NAME_PREFIX_TEXT-TXTS]  t59 ON  t59.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_GROUP_3-TXTS]  t60 ON  t60.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-AUTHORIZED_OFFICIAL_NAME_SUFFIX_TEXT-TXTS]  t61 ON  t61.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-NPI_DEACTIVATION_DATE-DTM]  t62 ON  t62.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-NPI_REACTIVATION_DATE-DTM]  t63 ON  t63.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_OTHER_NAME_SUFFIX_TEXT-TXTS]  t64 ON  t64.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-REPLACEMENT_NPI-TXTS]  t65 ON  t65.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_WIKI_LEAK-BSET_AFGHAN_WAR_DIARY]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_WIKI_LEAK-BSET_AFGHAN_WAR_DIARY]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as LATITUDE_FLT
,t7.[val] as EVENT_TEXT_TXTL
,t5.[val] as EVENT_TEXT_TXTS
,t4.[val] as INCIDENT_DATE_DTM
,t6.[val] as INCIDENT_DATE_TXTS
,t2.[val] as LINE_NUMBER_INT
,t3.[val] as LONGITUDE_FLT
FROM 
[BAL_WIKI_LEAK].dbo.[BSET_AFGHAN_WAR_DIARY-LATITUDE-FLT] t1
LEFT OUTER JOIN [BAL_WIKI_LEAK].dbo.[BSET_AFGHAN_WAR_DIARY-LINE_NUMBER-INT]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAK].dbo.[BSET_AFGHAN_WAR_DIARY-LONGITUDE-FLT]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAK].dbo.[BSET_AFGHAN_WAR_DIARY-INCIDENT_DATE-DTM]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAK].dbo.[BSET_AFGHAN_WAR_DIARY-EVENT_TEXT-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAK].dbo.[BSET_AFGHAN_WAR_DIARY-INCIDENT_DATE-TXTS]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAK].dbo.[BSET_AFGHAN_WAR_DIARY-EVENT_TEXT-TXTL]  t7 ON  t7.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_WIKI_LEAK-BSET_IRAQ_WAR_DIARY]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_WIKI_LEAK-BSET_IRAQ_WAR_DIARY]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as INCIDENT_DATE_DTM
,t6.[val] as EVENT_TEXT_TXTL
,t5.[val] as EVENT_TEXT_TXTS
,t2.[val] as LATITUDE_FLT
,t3.[val] as LINE_NUMBER_INT
,t4.[val] as LONGITUDE_FLT
FROM 
[BAL_WIKI_LEAK].dbo.[BSET_IRAQ_WAR_DIARY-INCIDENT_DATE-DTM] t1
LEFT OUTER JOIN [BAL_WIKI_LEAK].dbo.[BSET_IRAQ_WAR_DIARY-LATITUDE-FLT]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAK].dbo.[BSET_IRAQ_WAR_DIARY-LINE_NUMBER-INT]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAK].dbo.[BSET_IRAQ_WAR_DIARY-LONGITUDE-FLT]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAK].dbo.[BSET_IRAQ_WAR_DIARY-EVENT_TEXT-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAK].dbo.[BSET_IRAQ_WAR_DIARY-EVENT_TEXT-TXTL]  t6 ON  t6.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BAL_WIKI_LEAK-BSET_WAR_DIARY_KEYWORD]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------

CREATE VIEW [dbo].[BVW_BAL_WIKI_LEAK-BSET_WAR_DIARY_KEYWORD]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as LATITUDE_FLT
,t5.[val] as INCIDENT_DATE_DTM
,t7.[val] as INCIDENT_DATE_TXTS
,t6.[val] as KEY_WORD_TXTS
,t2.[val] as LINE_NUMBER_INT
,t3.[val] as LONGITUDE_FLT
,t4.[val] as WAR_DIARY_TXTS
FROM 
[BAL_WIKI_LEAK].dbo.[BSET_WAR_DIARY_KEYWORD-LATITUDE-FLT] t1
LEFT OUTER JOIN [BAL_WIKI_LEAK].dbo.[BSET_WAR_DIARY_KEYWORD-LINE_NUMBER-INT]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAK].dbo.[BSET_WAR_DIARY_KEYWORD-LONGITUDE-FLT]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAK].dbo.[BSET_WAR_DIARY_KEYWORD-WAR_DIARY-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAK].dbo.[BSET_WAR_DIARY_KEYWORD-INCIDENT_DATE-DTM]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAK].dbo.[BSET_WAR_DIARY_KEYWORD-KEY_WORD-TXTS]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAK].dbo.[BSET_WAR_DIARY_KEYWORD-INCIDENT_DATE-TXTS]  t7 ON  t7.[key] = t1.[key];

GO

/****** Object:  View [dbo].[BVW_BRIEF_LOCATION_CRIME_CA]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_LOCATION_CRIME_CA]
as
SELECT [OBJECT_KEY]
      ,[COMMON_LOCATION_TXTS]
      ,[ADDRESS_TYPE_TXTS]
      ,[ADDRESS_NBR_TXTS]
      ,[ADDRESS_TXTS]
      ,[CITY_TXTS]
      ,[STATE_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_LOCATION-BSET_CRIME_STATS_CA]




GO

/****** Object:  View [dbo].[BVW_BRIEF_LOCATION_CRIME_DC]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_LOCATION_CRIME_DC]
as
SELECT [OBJECT_KEY]
      ,[BUSINESSIMPROVEMENTDISTRICT_TXTS]
      ,[ANC_TXTS]
      ,[BLOCKSITEADDRESS_TXTS]
      ,[CITY_TXTS]
      ,[DISTRICT_TXTS]
      ,[LATITUDE_FLT]
      ,[LONGITUDE_FLT]
      ,[NEIGHBORHOODCLUSTER_TXTS]
      ,[STATE_TXTS]
      ,[WARD_TXTS]
  FROM [BAL_VIEWS].[dbo].[BVW_BAL_LOCATION-BSET_CRIME_STATS_DC]
--GO

--SELECT [OBJECT_KEY]
--      ,[BUSINESSIMPROVEMENTDISTRICT_TXTS]
--      ,[ANC_TXTS]
--      ,[BLOCKSITEADDRESS_TXTS]
--      ,[CCN_INT]
--      ,[CCN_TXTS]
--      ,[CITY_TXTS]
--      ,[DISTRICT_TXTS]
--      ,[HOTSPOT2004NAME_TXTS]
--      ,[HOTSPOT2005NAME_TXTS]
--      ,[HOTSPOT2006NAME_TXTS]
--      ,[LASTMODIFIEDDATE_DTM]
--      ,[LATITUDE_FLT]
--      ,[LONGITUDE_FLT]
--      ,[METHOD_TXTS]
--      ,[NARRATIVE_TXTS]
--      ,[NEIGHBORHOODCLUSTER_TXTS]
--      ,[NID_INT]
--      ,[OFFENSE_TXTS]
--      ,[PSA_TXTS]
--      ,[REPORTDATETIME_DTM]
--      ,[SHIFT_TXTS]
--      ,[SMD_TXTS]
--      ,[STATE_TXTS]
--      ,[WARD_TXTS]
--  FROM [BAL_VIEWS].[dbo].[BVW_BAL_LOCATION-BSET_CRIME_STATS_DC]
--GO





GO

/****** Object:  View [dbo].[BVW_BRIEF_LOCATION_EMPLOYER]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_LOCATION_EMPLOYER]
as

SELECT [OBJECT_KEY]
      ,[STREETADDRESS_TXTS]
      ,[CITY_TXTS]
      ,[STATE_TXTS]
      ,[ZIP_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_LOCATION-BSET_EMPLOYER]







GO

/****** Object:  View [dbo].[BVW_BRIEF_LOCATION_INSURER]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_LOCATION_INSURER]
as
SELECT [OBJECT_KEY]
      ,[ADDRESS1_TXTS]
      ,[ADDRESS2_TXTS]
      ,[CITY_TXTS]
      ,[STATE_TXTS]
      ,[ZIP_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_LOCATION-BSET_INSURER_LOCATION]




GO

/****** Object:  View [dbo].[BVW_BRIEF_LOCATION_MED_NATIONAL_PROVIDER_CMMS_DB]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE view [dbo].[BVW_BRIEF_LOCATION_MED_NATIONAL_PROVIDER_CMMS_DB]
as
SELECT [OBJECT_KEY]
      ,[PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS_TXTS]
      ,[PROVIDER_SECOND_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS_TXTS]
      ,[PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME_TXTS]
      ,[PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME_TXTS]
      ,[PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE_TXTS]
      ,[PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_COUNTRY_CODE_IF_OUTSIDE_U_S_TXTS]
      ,[PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS_TXTS]
       ,[PROVIDER_SECOND_LINE_BUSINESS_MAILING_ADDRESS_TXTS]
      ,[PROVIDER_BUSINESS_MAILING_ADDRESS_CITY_NAME_TXTS]
      ,[PROVIDER_BUSINESS_MAILING_ADDRESS_STATE_NAME_TXTS]
      ,[PROVIDER_BUSINESS_MAILING_ADDRESS_POSTAL_CODE_TXTS]
      ,[PROVIDER_BUSINESS_MAILING_ADDRESS_COUNTRY_CODE_IF_OUTSIDE_U_S_TXTS]
      ,[AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER_TXTS]
      ,[PROVIDER_BUSINESS_MAILING_ADDRESS_FAX_NUMBER_TXTS]
      ,[PROVIDER_BUSINESS_MAILING_ADDRESS_TELEPHONE_NUMBER_TXTS]
      ,[PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_FAX_NUMBER_TXTS]
      ,[PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_PROVIDER-BSET_NPI]





GO

/****** Object:  View [dbo].[BVW_BRIEF_LOCATION_WIKI_AFGHAN_WAR_DIARY]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_LOCATION_WIKI_AFGHAN_WAR_DIARY]
as
SELECT [OBJECT_KEY]
      ,[LATITUDE_FLT]
      ,[LONGITUDE_FLT]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_WIKI_LEAK-BSET_AFGHAN_WAR_DIARY]
GO

/****** Object:  View [dbo].[BVW_BRIEF_LOCATION_WIKI_IRAQ_WAR_DIARY]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_LOCATION_WIKI_IRAQ_WAR_DIARY]
as
SELECT [OBJECT_KEY]
     ,[LATITUDE_FLT]
     ,[LONGITUDE_FLT]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_WIKI_LEAK-BSET_IRAQ_WAR_DIARY]
GO

/****** Object:  View [dbo].[BVW_BRIEF_LOCATION_WIKI_WAR_DIARY_KEYWORD]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_LOCATION_WIKI_WAR_DIARY_KEYWORD]
as
SELECT [OBJECT_KEY]
      ,[LATITUDE_FLT]
      ,[LONGITUDE_FLT]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_WIKI_LEAK-BSET_WAR_DIARY_KEYWORD]
GO

/****** Object:  View [dbo].[BVW_BRIEF_LOCATION_ZIPCODE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_LOCATION_ZIPCODE]
as
SELECT [OBJECT_KEY]
      ,[CITY_TXTS]
      ,[COUNTRY_TXTS]
      ,[COUNTY_TXTS]
      ,[LAT_FLT]
      ,[LONG_FLT]
      ,[LOCATION_TXTS]
      ,[LOCATIONTEXT_TXTS]
      ,[STATE_TXTS]
      ,[WORLDREGION_TXTS]
      ,[ZIPCODE_TXTS]
  FROM [BAL_VIEWS].[dbo].[BVW_BAL_LOCATION-BSET_ZIP_CODE_LOCATION]

GO

/****** Object:  View [dbo].[BVW_BRIEF_NUMERIC_CRIME_CA]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_NUMERIC_CRIME_CA]
as
SELECT 
[OBJECT_KEY],
AGENCY_ID_INT,
CRIME_ID_INT
FROM [BAL_VIEWS].[dbo].[BVW_BAL_LOCATION-BSET_CRIME_STATS_CA]




GO

/****** Object:  View [dbo].[BVW_BRIEF_NUMERIC_CRIME_DC]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_NUMERIC_CRIME_DC]
as

SELECT [OBJECT_KEY],
      CCN_INT,
      NID_INT
FROM [BAL_VIEWS].[dbo].[BVW_BAL_LOCATION-BSET_CRIME_STATS_DC]




GO

/****** Object:  View [dbo].[BVW_BRIEF_NUMERIC_MED_APC]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_NUMERIC_MED_APC]
as
SELECT [OBJECT_KEY]
,[MINUNADJCOPAY_FLT]
,[NATIONALUNADJCOPAY_FLT]
,[PAYMENTRATE_FLT]
,[RELATIVEWEIGHT_FLT]
,[YEAR_INT]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_HOSPITAL_APC]
  

GO

/****** Object:  View [dbo].[BVW_BRIEF_NUMERIC_MED_COST_GPCI]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_NUMERIC_MED_COST_GPCI]
as
SELECT [OBJECT_KEY]
        ,[MALPRACTICEGPCI_FLT]
      ,[PRACTICEGPCI_FLT]
      ,[WORKGPCI_FLT]
      ,[YEAR_INT]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_GPCI]
  

GO

/****** Object:  View [dbo].[BVW_BRIEF_NUMERIC_MED_DURABLE_MEDICAL_EQUIPMENT]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_NUMERIC_MED_DURABLE_MEDICAL_EQUIPMENT]
as
SELECT [OBJECT_KEY]
      ,[YEAR_INT]
      ,[FLOOR_FLT]
      ,[CEILING_FLT]
      ,[AK_FLT]
      ,[AL_FLT]
      ,[AR_FLT]
      ,[AZ_FLT]
      ,[CA_FLT]
      ,[CO_FLT]
      ,[CT_FLT]
      ,[DC_FLT]
      ,[DE_FLT]
      ,[FL_FLT]
      ,[GA_FLT]
      ,[HI_FLT]
      ,[IA_FLT]
      ,[ID_FLT]
      ,[IL_FLT]
      ,[IN_FLT]
      ,[KS_FLT]
      ,[KY_FLT]
      ,[LA_FLT]
      ,[MA_FLT]
      ,[MD_FLT]
      ,[ME_FLT]
      ,[MI_FLT]
      ,[MN_FLT]
      ,[MO_FLT]

      ,[MS_FLT]
      ,[MT_FLT]
      ,[NC_FLT]
      ,[ND_FLT]
      ,[NE_FLT]
      ,[NH_FLT]
      ,[NJ_FLT]
      ,[NM_FLT]
      ,[NV_FLT]
      ,[NY_FLT]
      ,[OH_FLT]
      ,[OK_FLT]
      ,[OR_FLT]
      ,[PA_FLT]
      ,[PR_FLT]
      ,[RI_FLT]
      ,[SC_FLT]
      ,[SD_FLT]
      ,[TN_FLT]
      ,[TX_FLT]
      ,[UT_FLT]
      ,[VA_FLT]
      ,[VI_FLT]
      ,[VT_FLT]
      ,[WA_FLT]
      ,[WI_FLT]
      ,[WV_FLT]
      ,[WY_FLT]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_DURABLE_MEDICAL_EQUIPMENT]







GO

/****** Object:  View [dbo].[BVW_BRIEF_NUMERIC_MED_LAB_FEE_SCHEDULE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_NUMERIC_MED_LAB_FEE_SCHEDULE]
as
SELECT [OBJECT_KEY]
,[YEAR_INT]
,[FLOOR_FLT]
,[LIMIT_FLT]
,[POINT_FLT]
,[AK_FLT]
,[AL_FLT]
,[AR_FLT]
,[AZ_FLT]
,[CA1_FLT]
,[CA2_FLT]
,[CO_FLT]
,[CT_FLT]
,[DC_FLT]
,[DE_FLT]
,[FL_FLT]
,[GA_FLT]
,[HI_FLT]
,[IA_FLT]
,[ID_FLT]
,[IL_FLT]
,[IN_FLT]
,[KS_FLT]
,[KY_FLT]
,[LA_FLT]
,[MA_FLT]
,[MD_FLT]
,[ME_FLT]
,[MI_FLT]
,[MN_FLT]
,[MO1_FLT]
,[MO2_FLT]
,[MS_FLT]
,[MT_FLT]
,[NC_FLT]
,[ND_FLT]
,[NE_FLT]
,[NH_FLT]
,[NJ_FLT]
,[NM_FLT]
,[NV_FLT]
,[NY1_FLT]
,[NY2_FLT]
,[NY3_FLT]
,[OH_FLT]
,[OK_FLT]
,[OR_FLT]
,[PA_FLT]
,[PR_FLT]
,[RI_FLT]
,[SC_FLT]
,[SD_FLT]
,[TN_FLT]
,[TX_FLT]
,[UT_FLT]
,[VA_FLT]
,[VT_FLT]
,[WA_FLT]
,[WI_FLT]
,[WV_FLT]
,[WY_FLT]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_LAB_FEE_SCHEDULE]




GO

/****** Object:  View [dbo].[BVW_BRIEF_NUMERIC_MED_NATIONAL_PHYSICIAN_FEE_SCHEDULE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_NUMERIC_MED_NATIONAL_PHYSICIAN_FEE_SCHEDULE]
as
SELECT [OBJECT_KEY]
        ,[WORKRVU_FLT]
      ,[YEAR_INT]
        ,[NONFACRVU_FLT]
        ,[FACRVU_FLT]
      ,[POSTOP_FLT]
      ,[PREOP_FLT]
      ,[MPRVU_FLT]
      ,[INTRAOP_FLT]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_NPFS]
  

GO

/****** Object:  View [dbo].[BVW_BRIEF_NUMERIC_MED_NATIONAL_PROVIDER_CMMS_DB]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_NUMERIC_MED_NATIONAL_PROVIDER_CMMS_DB]
as
SELECT [OBJECT_KEY]
      ,[NPI_INT]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_PROVIDER-BSET_NPI]




GO

/****** Object:  View [dbo].[BVW_BRIEF_NUMERIC_WIKI_AFGHAN_WAR_DIARY]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_NUMERIC_WIKI_AFGHAN_WAR_DIARY]
as
SELECT [OBJECT_KEY]
      ,[LINE_NUMBER_INT]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_WIKI_LEAK-BSET_AFGHAN_WAR_DIARY]
GO

/****** Object:  View [dbo].[BVW_BRIEF_NUMERIC_WIKI_IRAQ_WAR_DIARY]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_NUMERIC_WIKI_IRAQ_WAR_DIARY]
as
SELECT [OBJECT_KEY]
      ,[LINE_NUMBER_INT]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_WIKI_LEAK-BSET_IRAQ_WAR_DIARY]
GO

/****** Object:  View [dbo].[BVW_BRIEF_NUMERIC_WIKI_WAR_DIARY_KEYWORD]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_NUMERIC_WIKI_WAR_DIARY_KEYWORD]
as
SELECT [OBJECT_KEY]
      ,[LINE_NUMBER_INT]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_WIKI_LEAK-BSET_WAR_DIARY_KEYWORD]
GO

/****** Object:  View [dbo].[BVW_BRIEF_NUMERIC_ZIPCODE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_NUMERIC_ZIPCODE]
as
SELECT [OBJECT_KEY]
HOUSINGUNITS_INT,
INCOME_FLT,
LANDAREA_FLT,
POPULATION_INT,
WATERAREA_FLT
FROM [BAL_VIEWS].[dbo].[BVW_BAL_LOCATION-BSET_ZIP_CODE_LOCATION]







GO

/****** Object:  View [dbo].[BVW_BRIEF_TEMPORAL_CRIME_CA]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEMPORAL_CRIME_CA]
as
SELECT [OBJECT_KEY]
      ,[CALL_DATE_DTM]
      ,[OFFENSE_DATE_DTM]
      ,[REPORT_DATE_DTM]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_LOCATION-BSET_CRIME_STATS_CA]



GO

/****** Object:  View [dbo].[BVW_BRIEF_TEMPORAL_CRIME_DC]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEMPORAL_CRIME_DC]
as

SELECT [OBJECT_KEY]
      ,[LASTMODIFIEDDATE_DTM]
      ,[REPORTDATETIME_DTM]
      ,[SHIFT_TXTS]

FROM [BAL_VIEWS].[dbo].[BVW_BAL_LOCATION-BSET_CRIME_STATS_DC]




GO

/****** Object:  View [dbo].[BVW_BRIEF_TEMPORAL_MED_NATIONAL_PROVIDER_CMMS_DB]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEMPORAL_MED_NATIONAL_PROVIDER_CMMS_DB]
as
SELECT [OBJECT_KEY]
      ,[LAST_UPDATE_DATE_DTM]
      ,[NPI_DEACTIVATION_DATE_DTM]
      ,[NPI_REACTIVATION_DATE_DTM]
      ,[PROVIDER_ENUMERATION_DATE_DTM]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_PROVIDER-BSET_NPI]




GO

/****** Object:  View [dbo].[BVW_BRIEF_TEMPORAL_WIKI_AFGHAN_WAR_DIARY]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEMPORAL_WIKI_AFGHAN_WAR_DIARY]
as
SELECT [OBJECT_KEY]
      ,[INCIDENT_DATE_DTM]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_WIKI_LEAK-BSET_AFGHAN_WAR_DIARY]
GO

/****** Object:  View [dbo].[BVW_BRIEF_TEMPORAL_WIKI_IRAQ_WAR_DIARY]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEMPORAL_WIKI_IRAQ_WAR_DIARY]
as
SELECT [OBJECT_KEY]
      ,[INCIDENT_DATE_DTM]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_WIKI_LEAK-BSET_IRAQ_WAR_DIARY]
GO

/****** Object:  View [dbo].[BVW_BRIEF_TEMPORAL_WIKI_WAR_DIARY_KEYWORD]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEMPORAL_WIKI_WAR_DIARY_KEYWORD]
as
SELECT [OBJECT_KEY]
      ,[INCIDENT_DATE_DTM]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_WIKI_LEAK-BSET_WAR_DIARY_KEYWORD]
GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_CRIME_CA]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_CRIME_CA]
as
SELECT [OBJECT_KEY]
      ,[ADDRESS_TYPE_TXTS]
      ,[COMMON_LOCATION_TXTS]
      ,[NARRATIVE_TXTS]
      ,[ORIG_CRIMETYPE_NAME_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_LOCATION-BSET_CRIME_STATS_CA]




GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_CRIME_DC]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_CRIME_DC]
as
SELECT [OBJECT_KEY]
      ,[BUSINESSIMPROVEMENTDISTRICT_TXTS]
      ,[HOTSPOT2004NAME_TXTS]
      ,[HOTSPOT2005NAME_TXTS]
      ,[HOTSPOT2006NAME_TXTS]
      ,[METHOD_TXTS]
      ,[NARRATIVE_TXTS]
      ,[OFFENSE_TXTS]
      ,[SHIFT_TXTS]
  FROM [BAL_VIEWS].[dbo].[BVW_BAL_LOCATION-BSET_CRIME_STATS_DC]
--GO

--SELECT [OBJECT_KEY]

--  FROM [BAL_VIEWS].[dbo].[BVW_BAL_LOCATION-BSET_CRIME_STATS_DC]
--GO





GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_EMPLOYER]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_EMPLOYER]
as
SELECT [OBJECT_KEY]
      ,[EMPLOYER_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_LOCATION-BSET_EMPLOYER]










GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_INSURER]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_INSURER]
as
SELECT [OBJECT_KEY],
INSURANCECOMPANY_TXTS,
LOCATIONNAME_TXTS
FROM [BAL_VIEWS].[dbo].[BVW_BAL_LOCATION-BSET_INSURER_LOCATION]




GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_MED_APC]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_MED_APC]
as
SELECT [OBJECT_KEY]
      ,[PROCEDURECODE_TXTS]
      ,[APC_TXTS]
      ,[DESCRIPTION_TXTS]
      ,[STATUSINDICATOR_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_HOSPITAL_APC]
GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_MED_CODE_MODIFIER]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_MED_CODE_MODIFIER]
as
SELECT [OBJECT_KEY]
      ,[MODDESC_TXTS]
      ,[MOD_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_MODIFIER]



GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_MED_COST_GPCI]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_MED_COST_GPCI]
as
SELECT [OBJECT_KEY],
CARRIERNO_TXTS,
LOCALITY_TXTS,
LOCALITYNAME_TXTS
FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_GPCI]
  

GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_MED_DRG_CODE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_MED_DRG_CODE]
as
SELECT [OBJECT_KEY]
      ,[DRGCODE_TXTS]
      ,[DRGTITLE_TXTS]
      ,[DRGTYPE_TXTS]
      ,[MEDICALSERVICEGROUP_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_DRG]




GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_MED_DRUG]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_MED_DRUG]
as
SELECT [OBJECT_KEY]
      ,[BRAND_NAME_TXTS]
      ,[CATEGORY_TXTS]
      ,[DRUG_ID_TXTS]
      ,[GENERIC_PRODUCT_NAME_TXTS]
      ,[GROUP_TXTS]
      ,[NDC_CODE_TXTS]
      ,[ROUTE_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_DRUG]




GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_MED_DURABLE_MEDICAL_EQUIPMENT]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_MED_DURABLE_MEDICAL_EQUIPMENT]
as
SELECT [OBJECT_KEY]
      ,[HCPCS_TXTS]
      ,[MOD_TXTS]
      ,[MOD2_TXTS]
      ,[CATG_TXTS]
      ,[DESCRIPTION_TXTS]
      ,[JURIS_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_DURABLE_MEDICAL_EQUIPMENT]


GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_MED_HOSPITAL_STATUS_CODE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_MED_HOSPITAL_STATUS_CODE]
as
SELECT [OBJECT_KEY]
      ,[HOSPSTATCODE_TXTS]
      ,[HOSPSTATDESC_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_HOSPITAL_STATUS_CODE]
GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_MED_ICD9_CODE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_MED_ICD9_CODE]
as
SELECT [OBJECT_KEY]
      ,[DIAGCODE_TXTS]
      ,[DIAGDESC_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_ICD9_CODE]
GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_MED_LAB_FEE_SCHEDULE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_MED_LAB_FEE_SCHEDULE]
as
SELECT [OBJECT_KEY]
      ,[HCPC_TXTS]
      ,[MODIFIER_TXTS]
      ,[DESCRIPTION_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_LAB_FEE_SCHEDULE]
GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_MED_NATIONAL_PHYSICIAN_FEE_SCHEDULE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_MED_NATIONAL_PHYSICIAN_FEE_SCHEDULE]
as
SELECT [OBJECT_KEY]
      ,[CPTCODE_TXTS]
      ,[MOD_TXTS]
      ,[DESCRIPTION_TXTS]
      ,[ASSTSURG_TXTS]
      ,[BILATSURG_TXTS]
      ,[COSURG_TXTS]
      ,[ENDOBASE_TXTS]
      ,[GLOBALDAYS_TXTS]
      ,[MULTPROC_TXTS]
      ,[PCTC_TXTS]
      ,[STATUSCODE_TXTS]
      ,[TEAMSURG_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_NPFS]
GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_MED_NATIONAL_PROVIDER_CMMS_DB]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_MED_NATIONAL_PROVIDER_CMMS_DB]
as
SELECT [OBJECT_KEY]
      ,[PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME_TXTS]
      ,[PROVIDER_GENDER_CODE_TXTS]
      ,[PROVIDER_NAME_PREFIX_TEXT_TXTS]
      ,[PROVIDER_FIRST_NAME_TXTS]
      ,[PROVIDER_MIDDLE_NAME_TXTS]
      ,[PROVIDER_LAST_NAME_LEGAL_NAME_TXTS]
      ,[PROVIDER_NAME_SUFFIX_TEXT_TXTS]
      ,[PROVIDER_CREDENTIAL_TEXT_TXTS]
      ,[IS_ORGANIZATION_SUBPART_TXTS]
      ,[IS_SOLE_PROPRIETOR_TXTS]
      ,[PARENT_ORGANIZATION_LBN_TXTS]
      ,[PARENT_ORGANIZATION_TIN_TXTS]
      ,[HEALTHCARE_PROVIDER_TAXONOMY_CODE_1_TXTS]
      ,[HEALTHCARE_PROVIDER_TAXONOMY_CODE_2_TXTS]
      ,[HEALTHCARE_PROVIDER_TAXONOMY_CODE_3_TXTS]
      ,[HEALTHCARE_PROVIDER_TAXONOMY_GROUP_1_TXTS]
      ,[HEALTHCARE_PROVIDER_TAXONOMY_GROUP_2_TXTS]
      ,[HEALTHCARE_PROVIDER_TAXONOMY_GROUP_3_TXTS]
      ,[PROVIDER_LICENSE_NUMBER_1_TXTS]
      ,[PROVIDER_LICENSE_NUMBER_2_TXTS]
      ,[PROVIDER_LICENSE_NUMBER_3_TXTS]
      ,[PROVIDER_LICENSE_NUMBER_STATE_CODE_1_TXTS]
      ,[PROVIDER_LICENSE_NUMBER_STATE_CODE_2_TXTS]
      ,[PROVIDER_LICENSE_NUMBER_STATE_CODE_3_TXTS]
      ,[REPLACEMENT_NPI_TXTS]
      ,[EMPLOYER_IDENTIFICATION_NUMBER_EIN_TXTS]
      ,[ENTITY_TYPE_CODE_TXTS]
      ,[AUTHORIZED_OFFICIAL_CREDENTIAL_TEXT_TXTS]
      ,[AUTHORIZED_OFFICIAL_FIRST_NAME_TXTS]
      ,[AUTHORIZED_OFFICIAL_LAST_NAME_TXTS]
      ,[AUTHORIZED_OFFICIAL_MIDDLE_NAME_TXTS]
      ,[AUTHORIZED_OFFICIAL_NAME_PREFIX_TEXT_TXTS]
      ,[AUTHORIZED_OFFICIAL_NAME_SUFFIX_TEXT_TXTS]
      ,[AUTHORIZED_OFFICIAL_TITLE_OR_POSITION_TXTS]
      ,[PROVIDER_OTHER_CREDENTIAL_TEXT_TXTS]
      ,[PROVIDER_OTHER_FIRST_NAME_TXTS]
      ,[PROVIDER_OTHER_LAST_NAME_TXTS]
      ,[PROVIDER_OTHER_LAST_NAME_TYPE_CODE_TXTS]
      ,[PROVIDER_OTHER_MIDDLE_NAME_TXTS]
      ,[PROVIDER_OTHER_NAME_PREFIX_TEXT_TXTS]
      ,[PROVIDER_OTHER_NAME_SUFFIX_TEXT_TXTS]
      ,[PROVIDER_OTHER_ORGANIZATION_NAME_TXTS]
      ,[PROVIDER_OTHER_ORGANIZATION_NAME_TYPE_CODE_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_PROVIDER-BSET_NPI]




GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_MED_PCTC]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_MED_PCTC]
as
SELECT [OBJECT_KEY]
      ,[PCTCDESC_TXTS]
      ,[PCTC_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_PCTC]
GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_MED_PHYSICIAN_STATUS_CODE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_MED_PHYSICIAN_STATUS_CODE]
as
SELECT [OBJECT_KEY]
      ,[STATUSCODEDESC_TXTS]
      ,[STATUSCODE_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_PHYSICIAN_STATUS_CODE]
GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_MED_PLACE_OF_SERVICE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_MED_PLACE_OF_SERVICE]
as
SELECT [OBJECT_KEY]
      ,[POSDESC_TXTS]
      ,[POS_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_PLACE_OF_SERVICE]




GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_MED_PROCEDURE_BUNDLING_EDIT]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_MED_PROCEDURE_BUNDLING_EDIT]
as
SELECT [OBJECT_KEY]
      ,[DESCRIPTION_TXTS]
      ,[MODALLOWED_TXTS]
      ,[PRIMARYCODE_TXTS]
      ,[SECONDARYCODE_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_BUNDLING_EDIT]




GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_MED_PROCEDURE_BUNDLING_EDIT_MUTUAL_EXCLUDE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_MED_PROCEDURE_BUNDLING_EDIT_MUTUAL_EXCLUDE]
as
SELECT [OBJECT_KEY]
      ,[CODE1_TXTS]
      ,[CODE2_TXTS]
  FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_BUNDLING_EDIT_MUTUAL_EXCLUDE]




GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_MED_TAXONOMY]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_MED_TAXONOMY]
as
SELECT [OBJECT_KEY]
      ,[CODE_TXTS]
      ,[DEFINITION_TXTL]
      ,[DEFINITION_TXTS]
      ,[CLASSIFICATION_TXTS]
      ,[SPECIALIZATION_TXTS]
      ,[TYPE_TXTS]
      ,[NOTES_TXTL]
      ,[NOTES_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_TAXONOMY_CODE]
GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_MED_TYPE_OF_SERVICE]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_MED_TYPE_OF_SERVICE]
as
SELECT [OBJECT_KEY]
      ,[TOSDESC_TXTS]
      ,[TOS_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_MEDICAL_CODE_SETS-BSET_TYPE_OF_SERVICE]




GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_WIKI_AFGHAN_WAR_DIARY]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_WIKI_AFGHAN_WAR_DIARY]
as
SELECT [OBJECT_KEY]
        ,[EVENT_TEXT_TXTL]
      ,[EVENT_TEXT_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_WIKI_LEAK-BSET_AFGHAN_WAR_DIARY]
GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_WIKI_DIPLOMATIC]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_WIKI_DIPLOMATIC]
as
select
main.[key] as OBJECT_KEY,
main.[val] as LINE_NUMBER,
f.[val] as FILE_NAME,
lc1.[val] as LINE_CONTENT_LARGE,
lc2.[val] as LINE_CONTENT_SMALL
from [BAL_WIKI_LEAK].dbo.[BSET_WIKI_DIPLOMATIC-LINE_NUMBER-INT] main
left outer join [BAL_WIKI_LEAK].dbo.[BSET_WIKI_DIPLOMATIC-FILE-TXTS] f
on f.[key] = main.[key]
left outer join [BAL_WIKI_LEAK].dbo.[BSET_WIKI_DIPLOMATIC-LINE_CONTENT-TXTL] lc1
on lc1.[key] = main.[key]
left outer join [BAL_WIKI_LEAK].dbo.[BSET_WIKI_DIPLOMATIC-LINE_CONTENT-TXTS] lc2
on lc2.[key] = main.[key] 
GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_WIKI_IRAQ_WAR_DIARY]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[BVW_BRIEF_TEXT_WIKI_IRAQ_WAR_DIARY]
as
SELECT [OBJECT_KEY]
      ,[EVENT_TEXT_TXTL]
      ,[EVENT_TEXT_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_WIKI_LEAK-BSET_IRAQ_WAR_DIARY]
GO

/****** Object:  View [dbo].[BVW_BRIEF_TEXT_WIKI_WAR_DIARY_KEYWORD]    Script Date: 04/24/2012 18:44:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE view [dbo].[BVW_BRIEF_TEXT_WIKI_WAR_DIARY_KEYWORD]
as
SELECT [OBJECT_KEY]
      ,[WAR_DIARY_TXTS]
      ,[KEY_WORD_TXTS]
FROM [BAL_VIEWS].[dbo].[BVW_BAL_WIKI_LEAK-BSET_WAR_DIARY_KEYWORD]

GO


