create view BVW_VIEW_META
as
SELECT
TABLE_NAME,
COLUMN_NAME,
DATA_TYPE,
CHARACTER_MAXIMUM_LENGTH,  
CHARACTER_OCTET_LENGTH,  
NUMERIC_PRECISION,  
CHARACTER_SET_NAME,  
COLLATION_NAME
FROM information_schema.COLUMNS 
where 
TABLE_NAME like 'BVW_%' 
