create view BVWX_GENDER_TAXONOMY
as
SELECT     
	[BSET_NPI-PROVIDER_GENDER_CODE].as_small_text as Gender, 
	[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1].as_small_text AS Taxonomy,
	COUNT(*) as Cardinality
FROM         
	[BSET_NPI-PROVIDER_GENDER_CODE] LEFT OUTER JOIN
    [BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1] ON 
    [BSET_NPI-PROVIDER_GENDER_CODE].object_key = 
    [BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1].object_key
group by
	[BSET_NPI-PROVIDER_GENDER_CODE].as_small_text, 
	[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1].as_small_text