USE BAL_VIEWS;
GO
CREATE VIEW [BVW_BAL_CRIME-BSET_CRIME_STATS_CA]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as ADDRESS_TYPE_TXTS
,t11.[val] as ADDRESS_TXTS
,t2.[val] as AGENCY_ID_INT
,t3.[val] as CALL_DATE_DTM
,t4.[val] as CITY_TXTS
,t12.[val] as COMMON_LOCATION_TXTS
,t5.[val] as CRIME_ID_INT
,t6.[val] as NARRATIVE_TXTS
,t7.[val] as OFFENSE_DATE_DTM
,t8.[val] as ORIG_CRIMETYPE_NAME_TXTS
,t9.[val] as REPORT_DATE_DTM
,t10.[val] as STATE_TXTS
FROM 
[BAL_CRIME].dbo.[BSET_CRIME_STATS_CA-ADDRESS_TYPE-TXTS] t1
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_CA-AGENCY_ID-INT]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_CA-CALL_DATE-DTM]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_CA-CITY-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_CA-CRIME_ID-INT]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_CA-NARRATIVE-TXTS]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_CA-OFFENSE_DATE-DTM]  t7 ON  t7.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_CA-ORIG_CRIMETYPE_NAME-TXTS]  t8 ON  t8.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_CA-REPORT_DATE-DTM]  t9 ON  t9.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_CA-STATE-TXTS]  t10 ON  t10.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_CA-ADDRESS-TXTS]  t11 ON  t11.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_CA-COMMON_LOCATION-TXTS]  t12 ON  t12.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_CRIME-BSET_CRIME_STATS_DC]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as BUSINESSIMPROVEMENTDISTRICT_TXTS
,t11.[val] as ANC_TXTS
,t15.[val] as BLOCKSITEADDRESS_TXTS
,t14.[val] as CCN_INT
,t24.[val] as CCN_TXTS
,t18.[val] as CITY_TXTS
,t12.[val] as DISTRICT_TXTS
,t2.[val] as HOTSPOT2004NAME_TXTS
,t3.[val] as HOTSPOT2005NAME_TXTS
,t4.[val] as HOTSPOT2006NAME_TXTS
,t5.[val] as LASTMODIFIEDDATE_DTM
,t16.[val] as LATITUDE_FLT
,t17.[val] as LONGITUDE_FLT
,t20.[val] as METHOD_TXTS
,t6.[val] as NARRATIVE_TXTS
,t21.[val] as NEIGHBORHOODCLUSTER_TXTS
,t7.[val] as NID_INT
,t8.[val] as OFFENSE_TXTS
,t22.[val] as PSA_TXTS
,t9.[val] as REPORTDATETIME_DTM
,t10.[val] as SHIFT_TXTS
,t13.[val] as SMD_TXTS
,t19.[val] as STATE_TXTS
,t23.[val] as WARD_TXTS
FROM 
[BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-BUSINESSIMPROVEMENTDISTRICT-TXTS] t1
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-HOTSPOT2004NAME-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-HOTSPOT2005NAME-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-HOTSPOT2006NAME-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-LASTMODIFIEDDATE-DTM]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-NARRATIVE-TXTS]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-NID-INT]  t7 ON  t7.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-OFFENSE-TXTS]  t8 ON  t8.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-REPORTDATETIME-DTM]  t9 ON  t9.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-SHIFT-TXTS]  t10 ON  t10.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-ANC-TXTS]  t11 ON  t11.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-DISTRICT-TXTS]  t12 ON  t12.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-SMD-TXTS]  t13 ON  t13.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-CCN-INT]  t14 ON  t14.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-BLOCKSITEADDRESS-TXTS]  t15 ON  t15.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-LATITUDE-FLT]  t16 ON  t16.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-LONGITUDE-FLT]  t17 ON  t17.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-CITY-TXTS]  t18 ON  t18.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-STATE-TXTS]  t19 ON  t19.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-METHOD-TXTS]  t20 ON  t20.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-NEIGHBORHOODCLUSTER-TXTS]  t21 ON  t21.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-PSA-TXTS]  t22 ON  t22.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-WARD-TXTS]  t23 ON  t23.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_CRIME_STATS_DC-CCN-TXTS]  t24 ON  t24.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_CRIME-BSET_ZIP_CODE_LOCATION]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as PREFERRED_TXTS
,t3.[val] as CITY_TXTS
,t4.[val] as COUNTRY_TXTS
,t12.[val] as COUNTY_TXTS
,t6.[val] as DECOMMISIONED_TXTS
,t13.[val] as HOUSINGUNITS_INT
,t14.[val] as LANDAREA_FLT
,t9.[val] as LAT_FLT
,t11.[val] as LOCATION_TXTS
,t8.[val] as LOCATIONTEXT_TXTS
,t10.[val] as LONG_FLT
,t17.[val] as MILITARYRESTRICTIONCODES_TXTS
,t15.[val] as POPULATION_INT
,t2.[val] as STATE_TXTS
,t7.[val] as TYPE_TXTS
,t16.[val] as WATERAREA_FLT
,t5.[val] as WORLDREGION_TXTS
FROM 
[BAL_CRIME].dbo.[BSET_ZIP_CODE_LOCATION-PREFERRED-TXTS] t1
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_ZIP_CODE_LOCATION-STATE-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_ZIP_CODE_LOCATION-CITY-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_ZIP_CODE_LOCATION-COUNTRY-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_ZIP_CODE_LOCATION-WORLDREGION-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_ZIP_CODE_LOCATION-DECOMMISIONED-TXTS]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_ZIP_CODE_LOCATION-TYPE-TXTS]  t7 ON  t7.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_ZIP_CODE_LOCATION-LOCATIONTEXT-TXTS]  t8 ON  t8.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_ZIP_CODE_LOCATION-LAT-FLT]  t9 ON  t9.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_ZIP_CODE_LOCATION-LONG-FLT]  t10 ON  t10.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_ZIP_CODE_LOCATION-LOCATION-TXTS]  t11 ON  t11.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_ZIP_CODE_LOCATION-COUNTY-TXTS]  t12 ON  t12.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_ZIP_CODE_LOCATION-HOUSINGUNITS-INT]  t13 ON  t13.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_ZIP_CODE_LOCATION-LANDAREA-FLT]  t14 ON  t14.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_ZIP_CODE_LOCATION-POPULATION-INT]  t15 ON  t15.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_ZIP_CODE_LOCATION-WATERAREA-FLT]  t16 ON  t16.[key] = t1.[key]
LEFT OUTER JOIN [BAL_CRIME].dbo.[BSET_ZIP_CODE_LOCATION-MILITARYRESTRICTIONCODES-TXTS]  t17 ON  t17.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_BILL_TYPE_CODE]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as BILLTYPECODE_TXTS
,t2.[val] as DESCRIPTION_TXTS
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_BILL_TYPE_CODE-BILLTYPECODE-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_BILL_TYPE_CODE-DESCRIPTION-TXTS]  t2 ON  t2.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_BUNDLING_EDIT]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as DESCRIPTION_TXTS
,t2.[val] as PRIMARYCODE_TXTS
,t3.[val] as SECONDARYCODE_TXTS
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_BUNDLING_EDIT-DESCRIPTION-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_BUNDLING_EDIT-PRIMARYCODE-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_BUNDLING_EDIT-SECONDARYCODE-TXTS]  t3 ON  t3.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_BUNDLING_EDIT_MUTUAL_EXCLUDE]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as CODE1_TXTS
,t2.[val] as CODE2_TXTS
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_BUNDLING_EDIT_MUTUAL_EXCLUDE-CODE1-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_BUNDLING_EDIT_MUTUAL_EXCLUDE-CODE2-TXTS]  t2 ON  t2.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_DRG]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as DRGTITLE_TXTS
,t2.[val] as DRGTYPE_TXTS
,t3.[val] as MEDICALSERVICEGROUP_TXTS
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_DRG-DRGTITLE-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DRG-DRGTYPE-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DRG-MEDICALSERVICEGROUP-TXTS]  t3 ON  t3.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_DRUG]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as BRAND_NAME_TXTS
,t2.[val] as CATEGORY_TXTS
,t6.[val] as DRUG_ID_TXTS
,t3.[val] as GENERIC_PRODUCT_NAME_TXTS
,t4.[val] as GROUP_TXTS
,t5.[val] as ROUTE_TXTS
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_DRUG-BRAND_NAME-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DRUG-CATEGORY-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DRUG-GENERIC_PRODUCT_NAME-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DRUG-GROUP-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DRUG-ROUTE-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DRUG-DRUG_ID-TXTS]  t6 ON  t6.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_DURABLE_MEDICAL_EQUIPMENT]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as CATG_TXTS
,t57.[val] as AK_FLT
,t64.[val] as AK_TXTS
,t47.[val] as AL_FLT
,t66.[val] as AL_TXTS
,t19.[val] as AR_FLT
,t67.[val] as AR_TXTS
,t21.[val] as AZ_FLT
,t68.[val] as AZ_TXTS
,t52.[val] as CA_FLT
,t69.[val] as CA_TXTS
,t56.[val] as CEILING_FLT
,t70.[val] as CEILING_TXTS
,t7.[val] as CO_FLT
,t71.[val] as CO_TXTS
,t36.[val] as CT_FLT
,t72.[val] as CT_TXTS
,t20.[val] as DC_FLT
,t73.[val] as DC_TXTS
,t33.[val] as DE_FLT
,t74.[val] as DE_TXTS
,t5.[val] as DESCRIPTION_TXTS
,t53.[val] as FL_FLT
,t75.[val] as FL_TXTS
,t55.[val] as FLOOR_FLT
,t63.[val] as FLOOR_TXTS
,t37.[val] as GA_FLT
,t76.[val] as GA_TXTS
,t2.[val] as HCPCS_TXTS
,t60.[val] as HI_FLT
,t65.[val] as HI_TXTS
,t48.[val] as IA_FLT
,t77.[val] as IA_TXTS
,t35.[val] as ID_FLT
,t78.[val] as ID_TXTS
,t38.[val] as IL_FLT
,t79.[val] as IL_TXTS
,t24.[val] as IN_FLT
,t80.[val] as IN_TXTS
,t3.[val] as JURIS_TXTS
,t32.[val] as KS_FLT
,t81.[val] as KS_TXTS
,t46.[val] as KY_FLT
,t82.[val] as KY_TXTS
,t6.[val] as LA_FLT
,t83.[val] as LA_TXTS
,t44.[val] as MA_FLT
,t84.[val] as MA_TXTS
,t18.[val] as MD_FLT
,t85.[val] as MD_TXTS
,t45.[val] as ME_FLT
,t86.[val] as ME_TXTS
,t25.[val] as MI_FLT
,t87.[val] as MI_TXTS
,t34.[val] as MN_FLT
,t88.[val] as MN_TXTS
,t54.[val] as MO_FLT
,t89.[val] as MO_TXTS
,t61.[val] as MOD_TXTS
,t62.[val] as MOD2_TXTS
,t27.[val] as MS_FLT
,t90.[val] as MS_TXTS
,t29.[val] as MT_FLT
,t91.[val] as MT_TXTS
,t41.[val] as NC_FLT
,t92.[val] as NC_TXTS
,t9.[val] as ND_FLT
,t93.[val] as ND_TXTS
,t49.[val] as NE_FLT
,t94.[val] as NE_TXTS
,t39.[val] as NH_FLT
,t95.[val] as NH_TXTS
,t23.[val] as NJ_FLT
,t96.[val] as NJ_TXTS
,t22.[val] as NM_FLT
,t97.[val] as NM_TXTS
,t15.[val] as NV_FLT
,t98.[val] as NV_TXTS
,t26.[val] as NY_FLT
,t99.[val] as NY_TXTS
,t16.[val] as OH_FLT
,t100.[val] as OH_TXTS
,t13.[val] as OK_FLT
,t101.[val] as OK_TXTS
,t42.[val] as OR_FLT
,t102.[val] as OR_TXTS
,t30.[val] as PA_FLT
,t103.[val] as PA_TXTS
,t58.[val] as PR_FLT
,t117.[val] as PR_TXTS
,t51.[val] as RI_FLT
,t104.[val] as RI_TXTS
,t43.[val] as SC_FLT
,t105.[val] as SC_TXTS
,t8.[val] as SD_FLT
,t106.[val] as SD_TXTS
,t50.[val] as TN_FLT
,t107.[val] as TN_TXTS
,t11.[val] as TX_FLT
,t108.[val] as TX_TXTS
,t17.[val] as UT_FLT
,t109.[val] as UT_TXTS
,t14.[val] as VA_FLT
,t110.[val] as VA_TXTS
,t59.[val] as VI_FLT
,t111.[val] as VI_TXTS
,t40.[val] as VT_FLT
,t112.[val] as VT_TXTS
,t12.[val] as WA_FLT
,t113.[val] as WA_TXTS
,t28.[val] as WI_FLT
,t114.[val] as WI_TXTS
,t10.[val] as WV_FLT
,t115.[val] as WV_TXTS
,t31.[val] as WY_FLT
,t116.[val] as WY_TXTS
,t4.[val] as YEAR_INT
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-CATG-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-HCPCS-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-JURIS-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-YEAR-INT]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-DESCRIPTION-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-LA-FLT]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-CO-FLT]  t7 ON  t7.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-SD-FLT]  t8 ON  t8.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-ND-FLT]  t9 ON  t9.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-WV-FLT]  t10 ON  t10.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-TX-FLT]  t11 ON  t11.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-WA-FLT]  t12 ON  t12.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-OK-FLT]  t13 ON  t13.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-VA-FLT]  t14 ON  t14.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-NV-FLT]  t15 ON  t15.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-OH-FLT]  t16 ON  t16.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-UT-FLT]  t17 ON  t17.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MD-FLT]  t18 ON  t18.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-AR-FLT]  t19 ON  t19.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-DC-FLT]  t20 ON  t20.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-AZ-FLT]  t21 ON  t21.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-NM-FLT]  t22 ON  t22.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-NJ-FLT]  t23 ON  t23.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-IN-FLT]  t24 ON  t24.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MI-FLT]  t25 ON  t25.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-NY-FLT]  t26 ON  t26.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MS-FLT]  t27 ON  t27.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-WI-FLT]  t28 ON  t28.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MT-FLT]  t29 ON  t29.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-PA-FLT]  t30 ON  t30.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-WY-FLT]  t31 ON  t31.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-KS-FLT]  t32 ON  t32.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-DE-FLT]  t33 ON  t33.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MN-FLT]  t34 ON  t34.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-ID-FLT]  t35 ON  t35.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-CT-FLT]  t36 ON  t36.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-GA-FLT]  t37 ON  t37.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-IL-FLT]  t38 ON  t38.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-NH-FLT]  t39 ON  t39.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-VT-FLT]  t40 ON  t40.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-NC-FLT]  t41 ON  t41.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-OR-FLT]  t42 ON  t42.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-SC-FLT]  t43 ON  t43.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MA-FLT]  t44 ON  t44.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-ME-FLT]  t45 ON  t45.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-KY-FLT]  t46 ON  t46.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-AL-FLT]  t47 ON  t47.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-IA-FLT]  t48 ON  t48.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-NE-FLT]  t49 ON  t49.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-TN-FLT]  t50 ON  t50.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-RI-FLT]  t51 ON  t51.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-CA-FLT]  t52 ON  t52.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-FL-FLT]  t53 ON  t53.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MO-FLT]  t54 ON  t54.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-FLOOR-FLT]  t55 ON  t55.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-CEILING-FLT]  t56 ON  t56.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-AK-FLT]  t57 ON  t57.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-PR-FLT]  t58 ON  t58.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-VI-FLT]  t59 ON  t59.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-HI-FLT]  t60 ON  t60.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MOD-TXTS]  t61 ON  t61.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MOD2-TXTS]  t62 ON  t62.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-FLOOR-TXTS]  t63 ON  t63.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-AK-TXTS]  t64 ON  t64.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-HI-TXTS]  t65 ON  t65.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-AL-TXTS]  t66 ON  t66.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-AR-TXTS]  t67 ON  t67.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-AZ-TXTS]  t68 ON  t68.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-CA-TXTS]  t69 ON  t69.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-CEILING-TXTS]  t70 ON  t70.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-CO-TXTS]  t71 ON  t71.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-CT-TXTS]  t72 ON  t72.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-DC-TXTS]  t73 ON  t73.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-DE-TXTS]  t74 ON  t74.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-FL-TXTS]  t75 ON  t75.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-GA-TXTS]  t76 ON  t76.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-IA-TXTS]  t77 ON  t77.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-ID-TXTS]  t78 ON  t78.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-IL-TXTS]  t79 ON  t79.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-IN-TXTS]  t80 ON  t80.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-KS-TXTS]  t81 ON  t81.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-KY-TXTS]  t82 ON  t82.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-LA-TXTS]  t83 ON  t83.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MA-TXTS]  t84 ON  t84.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MD-TXTS]  t85 ON  t85.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-ME-TXTS]  t86 ON  t86.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MI-TXTS]  t87 ON  t87.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MN-TXTS]  t88 ON  t88.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MO-TXTS]  t89 ON  t89.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MS-TXTS]  t90 ON  t90.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-MT-TXTS]  t91 ON  t91.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-NC-TXTS]  t92 ON  t92.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-ND-TXTS]  t93 ON  t93.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-NE-TXTS]  t94 ON  t94.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-NH-TXTS]  t95 ON  t95.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-NJ-TXTS]  t96 ON  t96.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-NM-TXTS]  t97 ON  t97.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-NV-TXTS]  t98 ON  t98.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-NY-TXTS]  t99 ON  t99.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-OH-TXTS]  t100 ON  t100.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-OK-TXTS]  t101 ON  t101.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-OR-TXTS]  t102 ON  t102.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-PA-TXTS]  t103 ON  t103.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-RI-TXTS]  t104 ON  t104.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-SC-TXTS]  t105 ON  t105.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-SD-TXTS]  t106 ON  t106.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-TN-TXTS]  t107 ON  t107.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-TX-TXTS]  t108 ON  t108.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-UT-TXTS]  t109 ON  t109.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-VA-TXTS]  t110 ON  t110.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-VI-TXTS]  t111 ON  t111.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-VT-TXTS]  t112 ON  t112.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-WA-TXTS]  t113 ON  t113.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-WI-TXTS]  t114 ON  t114.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-WV-TXTS]  t115 ON  t115.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-WY-TXTS]  t116 ON  t116.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_DURABLE_MEDICAL_EQUIPMENT-PR-TXTS]  t117 ON  t117.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_EMPLOYER]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as CITY_TXTS
,t6.[val] as EMPLOYER_TXTS
,t3.[val] as PAYER_TXTS
,t2.[val] as PAYERDESCRIPTION_TXTS
,t4.[val] as STATE_TXTS
,t5.[val] as STREETADDRESS_TXTS
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_EMPLOYER-CITY-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_EMPLOYER-PAYERDESCRIPTION-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_EMPLOYER-PAYER-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_EMPLOYER-STATE-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_EMPLOYER-STREETADDRESS-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_EMPLOYER-EMPLOYER-TXTS]  t6 ON  t6.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_FACILITY]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as CITY_TXTS
,t2.[val] as HOSPITAL_ID_TXTS
,t3.[val] as HOSPITAL_NAME_TXTS
,t4.[val] as STATE_TXTS
,t5.[val] as STREET_ADDRESS_TXTS
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_FACILITY-CITY-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_FACILITY-HOSPITAL_ID-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_FACILITY-HOSPITAL_NAME-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_FACILITY-STATE-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_FACILITY-STREET_ADDRESS-TXTS]  t5 ON  t5.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_GPCI]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as LOCALITYNAME_TXTS
,t3.[val] as MALPRACTICEGPCI_FLT
,t4.[val] as PRACTICEGPCI_FLT
,t5.[val] as WORKGPCI_FLT
,t2.[val] as YEAR_INT
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_GPCI-LOCALITYNAME-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_GPCI-YEAR-INT]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_GPCI-MALPRACTICEGPCI-FLT]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_GPCI-PRACTICEGPCI-FLT]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_GPCI-WORKGPCI-FLT]  t5 ON  t5.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_HOSPITAL_APC]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as STATUSINDICATOR_TXTS
,t9.[val] as APC_TXTS
,t3.[val] as DESCRIPTION_TXTS
,t4.[val] as MINUNADJCOPAY_FLT
,t8.[val] as NATIONALUNADJCOPAY_FLT
,t5.[val] as PAYMENTRATE_FLT
,t7.[val] as PROCEDURECODE_TXTS
,t6.[val] as RELATIVEWEIGHT_FLT
,t2.[val] as YEAR_INT
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_HOSPITAL_APC-STATUSINDICATOR-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_HOSPITAL_APC-YEAR-INT]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_HOSPITAL_APC-DESCRIPTION-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_HOSPITAL_APC-MINUNADJCOPAY-FLT]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_HOSPITAL_APC-PAYMENTRATE-FLT]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_HOSPITAL_APC-RELATIVEWEIGHT-FLT]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_HOSPITAL_APC-PROCEDURECODE-TXTS]  t7 ON  t7.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_HOSPITAL_APC-NATIONALUNADJCOPAY-FLT]  t8 ON  t8.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_HOSPITAL_APC-APC-TXTS]  t9 ON  t9.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_HOSPITAL_STATUS_CODE]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as HOSPSTATCODE_TXTS
,t2.[val] as HOSPSTATDESC_TXTS
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_HOSPITAL_STATUS_CODE-HOSPSTATCODE-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_HOSPITAL_STATUS_CODE-HOSPSTATDESC-TXTS]  t2 ON  t2.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_ICD9_CODE]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as DIAGDESC_TXTS
,t2.[val] as DIAGCODE_TXTS
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_ICD9_CODE-DIAGDESC-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_ICD9_CODE-DIAGCODE-TXTS]  t2 ON  t2.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_INSURER_LOCATION]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as INSURANCECOMPANY_TXTS
,t3.[val] as ADDRESS1_TXTS
,t6.[val] as ADDRESS2_TXTS
,t4.[val] as CITY_TXTS
,t2.[val] as LOCATIONNAME_TXTS
,t5.[val] as STATE_TXTS
,t7.[val] as ZIP_TXTS
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_INSURER_LOCATION-INSURANCECOMPANY-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_INSURER_LOCATION-LOCATIONNAME-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_INSURER_LOCATION-ADDRESS1-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_INSURER_LOCATION-CITY-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_INSURER_LOCATION-STATE-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_INSURER_LOCATION-ADDRESS2-TXTS]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_INSURER_LOCATION-ZIP-TXTS]  t7 ON  t7.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_LAB_FEE_SCHEDULE]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as YEAR_INT
,t17.[val] as AK_FLT
,t40.[val] as AL_FLT
,t41.[val] as AR_FLT
,t30.[val] as AZ_FLT
,t31.[val] as CA1_FLT
,t32.[val] as CA2_FLT
,t13.[val] as CO_FLT
,t48.[val] as CT_FLT
,t44.[val] as DC_FLT
,t38.[val] as DE_FLT
,t2.[val] as DESCRIPTION_TXTS
,t7.[val] as FL_FLT
,t63.[val] as FLOOR_FLT
,t23.[val] as GA_FLT
,t62.[val] as HCPC_TXTS
,t27.[val] as HI_FLT
,t28.[val] as IA_FLT
,t46.[val] as ID_FLT
,t33.[val] as IL_FLT
,t14.[val] as IN_FLT
,t18.[val] as KS_FLT
,t45.[val] as KY_FLT
,t10.[val] as LA_FLT
,t59.[val] as LIMIT_FLT
,t55.[val] as MA_FLT
,t36.[val] as MD_FLT
,t53.[val] as ME_FLT
,t24.[val] as MI_FLT
,t8.[val] as MN_FLT
,t49.[val] as MO1_FLT
,t20.[val] as MO2_FLT
,t61.[val] as MODIFIER_TXTS
,t3.[val] as MS_FLT
,t42.[val] as MT_FLT
,t50.[val] as NC_FLT
,t19.[val] as ND_FLT
,t51.[val] as NE_FLT
,t57.[val] as NH_FLT
,t37.[val] as NJ_FLT
,t6.[val] as NM_FLT
,t25.[val] as NV_FLT
,t58.[val] as NY1_FLT
,t54.[val] as NY2_FLT
,t5.[val] as NY3_FLT
,t52.[val] as OH_FLT
,t11.[val] as OK_FLT
,t47.[val] as OR_FLT
,t16.[val] as PA_FLT
,t60.[val] as POINT_FLT
,t34.[val] as PR_FLT
,t39.[val] as RI_FLT
,t4.[val] as SC_FLT
,t15.[val] as SD_FLT
,t29.[val] as TN_FLT
,t12.[val] as TX_FLT
,t43.[val] as UT_FLT
,t26.[val] as VA_FLT
,t56.[val] as VT_FLT
,t22.[val] as WA_FLT
,t9.[val] as WI_FLT
,t35.[val] as WV_FLT
,t21.[val] as WY_FLT
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-YEAR-INT] t1
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-DESCRIPTION-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-MS-FLT]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-SC-FLT]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-NY3-FLT]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-NM-FLT]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-FL-FLT]  t7 ON  t7.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-MN-FLT]  t8 ON  t8.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-WI-FLT]  t9 ON  t9.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-LA-FLT]  t10 ON  t10.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-OK-FLT]  t11 ON  t11.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-TX-FLT]  t12 ON  t12.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-CO-FLT]  t13 ON  t13.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-IN-FLT]  t14 ON  t14.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-SD-FLT]  t15 ON  t15.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-PA-FLT]  t16 ON  t16.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-AK-FLT]  t17 ON  t17.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-KS-FLT]  t18 ON  t18.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-ND-FLT]  t19 ON  t19.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-MO2-FLT]  t20 ON  t20.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-WY-FLT]  t21 ON  t21.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-WA-FLT]  t22 ON  t22.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-GA-FLT]  t23 ON  t23.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-MI-FLT]  t24 ON  t24.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-NV-FLT]  t25 ON  t25.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-VA-FLT]  t26 ON  t26.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-HI-FLT]  t27 ON  t27.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-IA-FLT]  t28 ON  t28.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-TN-FLT]  t29 ON  t29.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-AZ-FLT]  t30 ON  t30.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-CA1-FLT]  t31 ON  t31.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-CA2-FLT]  t32 ON  t32.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-IL-FLT]  t33 ON  t33.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-PR-FLT]  t34 ON  t34.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-WV-FLT]  t35 ON  t35.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-MD-FLT]  t36 ON  t36.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-NJ-FLT]  t37 ON  t37.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-DE-FLT]  t38 ON  t38.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-RI-FLT]  t39 ON  t39.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-AL-FLT]  t40 ON  t40.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-AR-FLT]  t41 ON  t41.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-MT-FLT]  t42 ON  t42.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-UT-FLT]  t43 ON  t43.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-DC-FLT]  t44 ON  t44.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-KY-FLT]  t45 ON  t45.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-ID-FLT]  t46 ON  t46.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-OR-FLT]  t47 ON  t47.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-CT-FLT]  t48 ON  t48.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-MO1-FLT]  t49 ON  t49.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-NC-FLT]  t50 ON  t50.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-NE-FLT]  t51 ON  t51.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-OH-FLT]  t52 ON  t52.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-ME-FLT]  t53 ON  t53.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-NY2-FLT]  t54 ON  t54.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-MA-FLT]  t55 ON  t55.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-VT-FLT]  t56 ON  t56.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-NH-FLT]  t57 ON  t57.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-NY1-FLT]  t58 ON  t58.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-LIMIT-FLT]  t59 ON  t59.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-POINT-FLT]  t60 ON  t60.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-MODIFIER-TXTS]  t61 ON  t61.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-HCPC-TXTS]  t62 ON  t62.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_LAB_FEE_SCHEDULE-FLOOR-FLT]  t63 ON  t63.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_MODIFIER]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as MODDESC_TXTS
,t2.[val] as MOD_TXTS
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_MODIFIER-MODDESC-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_MODIFIER-MOD-TXTS]  t2 ON  t2.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_NPFS]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as DESCRIPTION_TXTS
,t9.[val] as CPTCODE_TXTS
,t6.[val] as FACRVU_FLT
,t5.[val] as GLOBALDAYS_TXTS
,t10.[val] as MOD_TXTS
,t4.[val] as MPRVU_FLT
,t7.[val] as NONFACRVU_FLT
,t2.[val] as STATUSCODE_TXTS
,t8.[val] as WORKRVU_FLT
,t3.[val] as YEAR_INT
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_NPFS-DESCRIPTION-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_NPFS-STATUSCODE-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_NPFS-YEAR-INT]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_NPFS-MPRVU-FLT]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_NPFS-GLOBALDAYS-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_NPFS-FACRVU-FLT]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_NPFS-NONFACRVU-FLT]  t7 ON  t7.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_NPFS-WORKRVU-FLT]  t8 ON  t8.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_NPFS-CPTCODE-TXTS]  t9 ON  t9.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_NPFS-MOD-TXTS]  t10 ON  t10.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_PCTC]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as PCTCDESC_TXTS
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_PCTC-PCTCDESC-TXTS] t1;
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_PHYSICIAN_STATUS_CODE]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as STATUSCODEDESC_TXTS
,t2.[val] as STATUSCODE_TXTS
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_PHYSICIAN_STATUS_CODE-STATUSCODEDESC-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_PHYSICIAN_STATUS_CODE-STATUSCODE-TXTS]  t2 ON  t2.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_PLACE_OF_SERVICE]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as POSDESC_TXTS
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_PLACE_OF_SERVICE-POSDESC-TXTS] t1;
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_TAXONOMY_CODE]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as CLASSIFICATION_TXTS
,t2.[val] as CODE_TXTS
,t7.[val] as DEFINITION_TXTL
,t5.[val] as DEFINITION_TXTS
,t8.[val] as NOTES_TXTL
,t6.[val] as NOTES_TXTS
,t4.[val] as SPECIALIZATION_TXTS
,t3.[val] as TYPE_TXTS
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_TAXONOMY_CODE-CLASSIFICATION-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_TAXONOMY_CODE-CODE-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_TAXONOMY_CODE-TYPE-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_TAXONOMY_CODE-SPECIALIZATION-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_TAXONOMY_CODE-DEFINITION-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_TAXONOMY_CODE-NOTES-TXTS]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_TAXONOMY_CODE-DEFINITION-TXTL]  t7 ON  t7.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_TAXONOMY_CODE-NOTES-TXTL]  t8 ON  t8.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_TYPE_OF_SERVICE]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as TOSDESC_TXTS
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_TYPE_OF_SERVICE-TOSDESC-TXTS] t1;
GO
---------------

CREATE VIEW [BVW_BAL_MEDICAL_BILLING-BSET_ZIP_CODE_LOCATION]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as PREFERRED_TXTS
,t3.[val] as CITY_TXTS
,t4.[val] as COUNTRY_TXTS
,t12.[val] as COUNTY_TXTS
,t6.[val] as DECOMMISIONED_TXTS
,t13.[val] as HOUSINGUNITS_INT
,t14.[val] as LANDAREA_FLT
,t9.[val] as LAT_FLT
,t11.[val] as LOCATION_TXTS
,t8.[val] as LOCATIONTEXT_TXTS
,t10.[val] as LONG_FLT
,t17.[val] as MILITARYRESTRICTIONCODES_TXTS
,t15.[val] as POPULATION_INT
,t2.[val] as STATE_TXTS
,t7.[val] as TYPE_TXTS
,t16.[val] as WATERAREA_FLT
,t5.[val] as WORLDREGION_TXTS
FROM 
[BAL_MEDICAL_BILLING].dbo.[BSET_ZIP_CODE_LOCATION-PREFERRED-TXTS] t1
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_ZIP_CODE_LOCATION-STATE-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_ZIP_CODE_LOCATION-CITY-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_ZIP_CODE_LOCATION-COUNTRY-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_ZIP_CODE_LOCATION-WORLDREGION-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_ZIP_CODE_LOCATION-DECOMMISIONED-TXTS]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_ZIP_CODE_LOCATION-TYPE-TXTS]  t7 ON  t7.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_ZIP_CODE_LOCATION-LOCATIONTEXT-TXTS]  t8 ON  t8.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_ZIP_CODE_LOCATION-LAT-FLT]  t9 ON  t9.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_ZIP_CODE_LOCATION-LONG-FLT]  t10 ON  t10.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_ZIP_CODE_LOCATION-LOCATION-TXTS]  t11 ON  t11.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_ZIP_CODE_LOCATION-COUNTY-TXTS]  t12 ON  t12.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_ZIP_CODE_LOCATION-HOUSINGUNITS-INT]  t13 ON  t13.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_ZIP_CODE_LOCATION-LANDAREA-FLT]  t14 ON  t14.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_ZIP_CODE_LOCATION-POPULATION-INT]  t15 ON  t15.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_ZIP_CODE_LOCATION-WATERAREA-FLT]  t16 ON  t16.[key] = t1.[key]
LEFT OUTER JOIN [BAL_MEDICAL_BILLING].dbo.[BSET_ZIP_CODE_LOCATION-MILITARYRESTRICTIONCODES-TXTS]  t17 ON  t17.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_PROVIDER-BSET_NPI]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as LAST_UPDATE_DATE_DTM
,t33.[val] as AUTHORIZED_OFFICIAL_CREDENTIAL_TEXT_TXTS
,t24.[val] as AUTHORIZED_OFFICIAL_FIRST_NAME_TXTS
,t28.[val] as AUTHORIZED_OFFICIAL_LAST_NAME_TXTS
,t30.[val] as AUTHORIZED_OFFICIAL_MIDDLE_NAME_TXTS
,t31.[val] as AUTHORIZED_OFFICIAL_NAME_PREFIX_TEXT_TXTS
,t44.[val] as AUTHORIZED_OFFICIAL_NAME_SUFFIX_TEXT_TXTS
,t50.[val] as AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER_TXTS
,t26.[val] as AUTHORIZED_OFFICIAL_TITLE_OR_POSITION_TXTS
,t25.[val] as EMPLOYER_IDENTIFICATION_NUMBER_EIN_TXTS
,t6.[val] as HEALTHCARE_PROVIDER_TAXONOMY_CODE_1_TXTS
,t32.[val] as HEALTHCARE_PROVIDER_TAXONOMY_CODE_2_TXTS
,t37.[val] as HEALTHCARE_PROVIDER_TAXONOMY_CODE_3_TXTS
,t29.[val] as IS_ORGANIZATION_SUBPART_TXTS
,t14.[val] as IS_SOLE_PROPRIETOR_TXTS
,t45.[val] as NPI_DEACTIVATION_DATE_DTM
,t2.[val] as NPI_INT
,t46.[val] as NPI_REACTIVATION_DATE_DTM
,t41.[val] as PARENT_ORGANIZATION_LBN_TXTS
,t40.[val] as PARENT_ORGANIZATION_TIN_TXTS
,t10.[val] as PROVIDER_BUSINESS_MAILING_ADDRESS_CITY_NAME_TXTS
,t3.[val] as PROVIDER_BUSINESS_MAILING_ADDRESS_COUNTRY_CODE_IF_OUTSIDE_U_S_TXTS
,t54.[val] as PROVIDER_BUSINESS_MAILING_ADDRESS_FAX_NUMBER_TXTS
,t48.[val] as PROVIDER_BUSINESS_MAILING_ADDRESS_POSTAL_CODE_TXTS
,t8.[val] as PROVIDER_BUSINESS_MAILING_ADDRESS_STATE_NAME_TXTS
,t52.[val] as PROVIDER_BUSINESS_MAILING_ADDRESS_TELEPHONE_NUMBER_TXTS
,t7.[val] as PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME_TXTS
,t4.[val] as PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_COUNTRY_CODE_IF_OUTSIDE_U_S_TXTS
,t53.[val] as PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_FAX_NUMBER_TXTS
,t49.[val] as PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE_TXTS
,t9.[val] as PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME_TXTS
,t51.[val] as PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER_TXTS
,t18.[val] as PROVIDER_CREDENTIAL_TEXT_TXTS
,t5.[val] as PROVIDER_ENUMERATION_DATE_DTM
,t11.[val] as PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS_TXTS
,t12.[val] as PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS_TXTS
,t15.[val] as PROVIDER_FIRST_NAME_TXTS
,t16.[val] as PROVIDER_GENDER_CODE_TXTS
,t17.[val] as PROVIDER_LAST_NAME_LEGAL_NAME_TXTS
,t20.[val] as PROVIDER_LICENSE_NUMBER_1_TXTS
,t13.[val] as PROVIDER_LICENSE_NUMBER_STATE_CODE_1_TXTS
,t19.[val] as PROVIDER_MIDDLE_NAME_TXTS
,t21.[val] as PROVIDER_NAME_PREFIX_TEXT_TXTS
,t42.[val] as PROVIDER_NAME_SUFFIX_TEXT_TXTS
,t27.[val] as PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME_TXTS
,t39.[val] as PROVIDER_OTHER_CREDENTIAL_TEXT_TXTS
,t35.[val] as PROVIDER_OTHER_FIRST_NAME_TXTS
,t36.[val] as PROVIDER_OTHER_LAST_NAME_TXTS
,t38.[val] as PROVIDER_OTHER_MIDDLE_NAME_TXTS
,t43.[val] as PROVIDER_OTHER_NAME_PREFIX_TEXT_TXTS
,t47.[val] as PROVIDER_OTHER_NAME_SUFFIX_TEXT_TXTS
,t34.[val] as PROVIDER_OTHER_ORGANIZATION_NAME_TXTS
,t23.[val] as PROVIDER_SECOND_LINE_BUSINESS_MAILING_ADDRESS_TXTS
,t22.[val] as PROVIDER_SECOND_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS_TXTS
FROM 
[BAL_PROVIDER].dbo.[BSET_NPI-LAST_UPDATE_DATE-DTM] t1
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-NPI-INT]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_MAILING_ADDRESS_COUNTRY_CODE_IF_OUTSIDE_U_S-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_COUNTRY_CODE_IF_OUTSIDE_U_S-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_ENUMERATION_DATE-DTM]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1-TXTS]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME-TXTS]  t7 ON  t7.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_MAILING_ADDRESS_STATE_NAME-TXTS]  t8 ON  t8.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME-TXTS]  t9 ON  t9.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_MAILING_ADDRESS_CITY_NAME-TXTS]  t10 ON  t10.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS-TXTS]  t11 ON  t11.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS-TXTS]  t12 ON  t12.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_LICENSE_NUMBER_STATE_CODE_1-TXTS]  t13 ON  t13.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-IS_SOLE_PROPRIETOR-TXTS]  t14 ON  t14.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_FIRST_NAME-TXTS]  t15 ON  t15.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_GENDER_CODE-TXTS]  t16 ON  t16.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_LAST_NAME_LEGAL_NAME-TXTS]  t17 ON  t17.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_CREDENTIAL_TEXT-TXTS]  t18 ON  t18.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_MIDDLE_NAME-TXTS]  t19 ON  t19.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_LICENSE_NUMBER_1-TXTS]  t20 ON  t20.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_NAME_PREFIX_TEXT-TXTS]  t21 ON  t21.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_SECOND_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS-TXTS]  t22 ON  t22.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_SECOND_LINE_BUSINESS_MAILING_ADDRESS-TXTS]  t23 ON  t23.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-AUTHORIZED_OFFICIAL_FIRST_NAME-TXTS]  t24 ON  t24.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-EMPLOYER_IDENTIFICATION_NUMBER_EIN-TXTS]  t25 ON  t25.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-AUTHORIZED_OFFICIAL_TITLE_OR_POSITION-TXTS]  t26 ON  t26.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME-TXTS]  t27 ON  t27.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-AUTHORIZED_OFFICIAL_LAST_NAME-TXTS]  t28 ON  t28.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-IS_ORGANIZATION_SUBPART-TXTS]  t29 ON  t29.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-AUTHORIZED_OFFICIAL_MIDDLE_NAME-TXTS]  t30 ON  t30.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-AUTHORIZED_OFFICIAL_NAME_PREFIX_TEXT-TXTS]  t31 ON  t31.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_2-TXTS]  t32 ON  t32.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-AUTHORIZED_OFFICIAL_CREDENTIAL_TEXT-TXTS]  t33 ON  t33.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_OTHER_ORGANIZATION_NAME-TXTS]  t34 ON  t34.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_OTHER_FIRST_NAME-TXTS]  t35 ON  t35.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_OTHER_LAST_NAME-TXTS]  t36 ON  t36.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_3-TXTS]  t37 ON  t37.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_OTHER_MIDDLE_NAME-TXTS]  t38 ON  t38.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_OTHER_CREDENTIAL_TEXT-TXTS]  t39 ON  t39.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PARENT_ORGANIZATION_TIN-TXTS]  t40 ON  t40.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PARENT_ORGANIZATION_LBN-TXTS]  t41 ON  t41.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_NAME_SUFFIX_TEXT-TXTS]  t42 ON  t42.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_OTHER_NAME_PREFIX_TEXT-TXTS]  t43 ON  t43.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-AUTHORIZED_OFFICIAL_NAME_SUFFIX_TEXT-TXTS]  t44 ON  t44.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-NPI_DEACTIVATION_DATE-DTM]  t45 ON  t45.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-NPI_REACTIVATION_DATE-DTM]  t46 ON  t46.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_OTHER_NAME_SUFFIX_TEXT-TXTS]  t47 ON  t47.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_MAILING_ADDRESS_POSTAL_CODE-TXTS]  t48 ON  t48.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE-TXTS]  t49 ON  t49.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER-TXTS]  t50 ON  t50.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER-TXTS]  t51 ON  t51.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_MAILING_ADDRESS_TELEPHONE_NUMBER-TXTS]  t52 ON  t52.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_FAX_NUMBER-TXTS]  t53 ON  t53.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_NPI-PROVIDER_BUSINESS_MAILING_ADDRESS_FAX_NUMBER-TXTS]  t54 ON  t54.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_PROVIDER-BSET_TAXONOMY]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as CLASSIFICATION_TXTS
,t2.[val] as CODE_TXTS
,t7.[val] as DEFINITION_TXTL
,t5.[val] as DEFINITION_TXTS
,t8.[val] as NOTES_TXTL
,t6.[val] as NOTES_TXTS
,t4.[val] as SPECIALIZATION_TXTS
,t3.[val] as TYPE_TXTS
FROM 
[BAL_PROVIDER].dbo.[BSET_TAXONOMY-CLASSIFICATION-TXTS] t1
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_TAXONOMY-CODE-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_TAXONOMY-TYPE-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_TAXONOMY-SPECIALIZATION-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_TAXONOMY-DEFINITION-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_TAXONOMY-NOTES-TXTS]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_TAXONOMY-DEFINITION-TXTL]  t7 ON  t7.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_TAXONOMY-NOTES-TXTL]  t8 ON  t8.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_PROVIDER-BSET_ZIP_CODE_LOCATION]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as PREFERRED_TXTS
,t3.[val] as CITY_TXTS
,t4.[val] as COUNTRY_TXTS
,t12.[val] as COUNTY_TXTS
,t6.[val] as DECOMMISIONED_TXTS
,t13.[val] as HOUSINGUNITS_INT
,t14.[val] as LANDAREA_FLT
,t9.[val] as LAT_FLT
,t11.[val] as LOCATION_TXTS
,t8.[val] as LOCATIONTEXT_TXTS
,t10.[val] as LONG_FLT
,t17.[val] as MILITARYRESTRICTIONCODES_TXTS
,t15.[val] as POPULATION_INT
,t2.[val] as STATE_TXTS
,t7.[val] as TYPE_TXTS
,t16.[val] as WATERAREA_FLT
,t5.[val] as WORLDREGION_TXTS
FROM 
[BAL_PROVIDER].dbo.[BSET_ZIP_CODE_LOCATION-PREFERRED-TXTS] t1
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_ZIP_CODE_LOCATION-STATE-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_ZIP_CODE_LOCATION-CITY-TXTS]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_ZIP_CODE_LOCATION-COUNTRY-TXTS]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_ZIP_CODE_LOCATION-WORLDREGION-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_ZIP_CODE_LOCATION-DECOMMISIONED-TXTS]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_ZIP_CODE_LOCATION-TYPE-TXTS]  t7 ON  t7.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_ZIP_CODE_LOCATION-LOCATIONTEXT-TXTS]  t8 ON  t8.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_ZIP_CODE_LOCATION-LAT-FLT]  t9 ON  t9.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_ZIP_CODE_LOCATION-LONG-FLT]  t10 ON  t10.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_ZIP_CODE_LOCATION-LOCATION-TXTS]  t11 ON  t11.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_ZIP_CODE_LOCATION-COUNTY-TXTS]  t12 ON  t12.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_ZIP_CODE_LOCATION-HOUSINGUNITS-INT]  t13 ON  t13.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_ZIP_CODE_LOCATION-LANDAREA-FLT]  t14 ON  t14.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_ZIP_CODE_LOCATION-POPULATION-INT]  t15 ON  t15.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_ZIP_CODE_LOCATION-WATERAREA-FLT]  t16 ON  t16.[key] = t1.[key]
LEFT OUTER JOIN [BAL_PROVIDER].dbo.[BSET_ZIP_CODE_LOCATION-MILITARYRESTRICTIONCODES-TXTS]  t17 ON  t17.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_WIKI_LEAKS-BSET_AFGHAN_WAR_DIARY]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as LINE_NUMBER_INT
,t7.[val] as EVENT_TEXT_TXTL
,t5.[val] as EVENT_TEXT_TXTS
,t4.[val] as INCIDENT_DATE_DTM
,t6.[val] as INCIDENT_DATE_TXTS
,t3.[val] as LATITUDE_FLT
,t2.[val] as LONGITUDE_FLT
FROM 
[BAL_WIKI_LEAKS].dbo.[BSET_AFGHAN_WAR_DIARY-LINE_NUMBER-INT] t1
LEFT OUTER JOIN [BAL_WIKI_LEAKS].dbo.[BSET_AFGHAN_WAR_DIARY-LONGITUDE-FLT]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAKS].dbo.[BSET_AFGHAN_WAR_DIARY-LATITUDE-FLT]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAKS].dbo.[BSET_AFGHAN_WAR_DIARY-INCIDENT_DATE-DTM]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAKS].dbo.[BSET_AFGHAN_WAR_DIARY-EVENT_TEXT-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAKS].dbo.[BSET_AFGHAN_WAR_DIARY-INCIDENT_DATE-TXTS]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAKS].dbo.[BSET_AFGHAN_WAR_DIARY-EVENT_TEXT-TXTL]  t7 ON  t7.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_WIKI_LEAKS-BSET_IRAQ_WAR_DIARY]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as INCIDENT_DATE_DTM
,t6.[val] as EVENT_TEXT_TXTL
,t5.[val] as EVENT_TEXT_TXTS
,t3.[val] as LATITUDE_FLT
,t2.[val] as LINE_NUMBER_INT
,t4.[val] as LONGITUDE_FLT
FROM 
[BAL_WIKI_LEAKS].dbo.[BSET_IRAQ_WAR_DIARY-INCIDENT_DATE-DTM] t1
LEFT OUTER JOIN [BAL_WIKI_LEAKS].dbo.[BSET_IRAQ_WAR_DIARY-LINE_NUMBER-INT]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAKS].dbo.[BSET_IRAQ_WAR_DIARY-LATITUDE-FLT]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAKS].dbo.[BSET_IRAQ_WAR_DIARY-LONGITUDE-FLT]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAKS].dbo.[BSET_IRAQ_WAR_DIARY-EVENT_TEXT-TXTS]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAKS].dbo.[BSET_IRAQ_WAR_DIARY-EVENT_TEXT-TXTL]  t6 ON  t6.[key] = t1.[key];
GO
---------------

CREATE VIEW [BVW_BAL_WIKI_LEAKS-BSET_WAR_DIARY_KEYWORD]
AS
SELECT 
t1.[key] as OBJECT_KEY 
,t1.[val] as LINE_NUMBER_INT
,t5.[val] as INCIDENT_DATE_DTM
,t7.[val] as INCIDENT_DATE_TXTS
,t6.[val] as KEY_WORD_TXTS
,t4.[val] as LATITUDE_FLT
,t3.[val] as LONGITUDE_FLT
,t2.[val] as WAR_DIARY_TXTS
FROM 
[BAL_WIKI_LEAKS].dbo.[BSET_WAR_DIARY_KEYWORD-LINE_NUMBER-INT] t1
LEFT OUTER JOIN [BAL_WIKI_LEAKS].dbo.[BSET_WAR_DIARY_KEYWORD-WAR_DIARY-TXTS]  t2 ON  t2.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAKS].dbo.[BSET_WAR_DIARY_KEYWORD-LONGITUDE-FLT]  t3 ON  t3.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAKS].dbo.[BSET_WAR_DIARY_KEYWORD-LATITUDE-FLT]  t4 ON  t4.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAKS].dbo.[BSET_WAR_DIARY_KEYWORD-INCIDENT_DATE-DTM]  t5 ON  t5.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAKS].dbo.[BSET_WAR_DIARY_KEYWORD-KEY_WORD-TXTS]  t6 ON  t6.[key] = t1.[key]
LEFT OUTER JOIN [BAL_WIKI_LEAKS].dbo.[BSET_WAR_DIARY_KEYWORD-INCIDENT_DATE-TXTS]  t7 ON  t7.[key] = t1.[key];
GO
---------------

