SELECT [NPI]
      ,[Org Name]
      ,[Last Name]
      ,[First Name]
      ,[Middle Name]
      ,[Prefix]
      ,[Suffix]
      ,[Prof. Credentials]
      ,[Address Line 1]
      ,[Address Line 2]
      ,[City]
      ,[State Or Province]
      ,[Postal Code]
      ,[Gender]
      ,[Taxonomy Code 1]
      ,[Tax. Type - 1]
      ,[Tax. Class - 1]
      ,[Tax. Specialization - 1]
      ,[Tax. Definition - 1]
      ,[Tax. Notes - 1]
      ,[Taxonomy Code 2]
      ,[Tax. Type - 2]
      ,[Tax. Class - 2]
      ,[Tax. Specialization - 2]
      ,[Tax. Definition - 2]
      ,[Tax. Notes - 2]
FROM [dndx_views].[dbo].[vdndx_npi]



