create view BVW_SEARCH_1
as
SELECT
BVW_NAMES_TAXONOMY.object_key, 
BVW_NAMES_TAXONOMY.Prefix, 
BVW_NAMES_TAXONOMY.First_Name, 
BVW_NAMES_TAXONOMY.Middle_Name, 
BVW_NAMES_TAXONOMY.Last_Name, 
BVW_NAMES_TAXONOMY.Suffix, 
BVW_NAMES_TAXONOMY.Credential_Text, 
BVW_NAMES_TAXONOMY.Organization_Name, 
BVW_NAMES_TAXONOMY.Taxonomy, 
BVW_NAMES_TAXONOMY.Taxonomy_Type, 
BVW_NAMES_TAXONOMY.Taxonomy_Class, 
BVW_NAMES_TAXONOMY.Taxonomy_Specialization, 
BVW_NAMES_TAXONOMY.Taxonomy_Definition, 
BVW_NAMES_TAXONOMY.Taxonomy_Notes, 
BVW_POSTAL_CODE_ADDITIONAL_INFO.PostalCode, 
BVW_POSTAL_CODE_ADDITIONAL_INFO.CITY, 
BVW_POSTAL_CODE_ADDITIONAL_INFO.COUNTRY, 
BVW_POSTAL_CODE_ADDITIONAL_INFO.COUNTY, 
BVW_POSTAL_CODE_ADDITIONAL_INFO.STATE, 
BVW_POSTAL_CODE_ADDITIONAL_INFO.LAT, 
BVW_POSTAL_CODE_ADDITIONAL_INFO.LONG, 
BVW_PROVIDER_ENUMERATION_DATE_YYYYMMDD.PROVIDER_ENUMERATION_DATE_YYYYMMDD
FROM         
BVW_NAMES_TAXONOMY 
LEFT OUTER JOIN BVW_PROVIDER_ENUMERATION_DATE_YYYYMMDD ON 
BVW_NAMES_TAXONOMY.object_key = BVW_PROVIDER_ENUMERATION_DATE_YYYYMMDD.object_key 
LEFT OUTER JOIN BVW_POSTAL_CODE_ADDITIONAL_INFO ON 
BVW_NAMES_TAXONOMY.object_key = BVW_POSTAL_CODE_ADDITIONAL_INFO.object_key
