create view BVWCU_STATE_OR_PROVINCE_TAXONOMY_GENDER
as
SELECT     
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME].as_small_text as StateOrProvince, 
[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1].as_small_text AS Taxonomy, 
[BSET_NPI-PROVIDER_GENDER_CODE].as_small_text AS Gender,
COUNT(*) as Cardinality
FROM         
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME] LEFT OUTER JOIN
[BSET_NPI-PROVIDER_GENDER_CODE] ON 
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME].object_key = 
[BSET_NPI-PROVIDER_GENDER_CODE].object_key LEFT OUTER JOIN
[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1] ON 
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME].object_key = 
[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1].object_key
group by
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME].as_small_text, 
[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1].as_small_text, 
[BSET_NPI-PROVIDER_GENDER_CODE].as_small_text