create view BVW_BSET_SHOW_WEB_META_3
as
SELECT     BVW_BSET_VIEW_META.TABLE_NAME, BVW_BSET_VIEW_META.COLUMN_NAME, BVW_BSET_VIEW_META.DATA_TYPE, 
                      BVW_BSET_VIEW_META.CHARACTER_MAXIMUM_LENGTH, BVW_BSET_VIEW_META.CHARACTER_OCTET_LENGTH, 
                      BVW_BSET_VIEW_META.NUMERIC_PRECISION, BVW_BSET_VIEW_META.CHARACTER_SET_NAME, BVW_BSET_VIEW_META.COLLATION_NAME, 
                      BVW_BSET_SHOW_WEB_META_2.DATABASE_NAME, BVW_BSET_SHOW_WEB_META_2.OBJECT_NAME, 
                      BVW_BSET_SHOW_WEB_META_2.TOTAL_CARDINALITY
FROM         BVW_BSET_VIEW_META INNER JOIN
                      BVW_BSET_SHOW_WEB_META_2 ON BVW_BSET_VIEW_META.TABLE_NAME = BVW_BSET_SHOW_WEB_META_2.TABLE_NAME