--USE [BLNS_PROVIDER_RESEARCH]
--GO

--/****** Object:  View [dbo].[BVW_NAMES_TAXONOMY]    Script Date: 04/02/2012 19:49:22 ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO

create view [dbo].[BVW_NAMES_TAXONOMY_LOCATION]
as
SELECT     
[BSET_NPI-NPI].object_key, 
[BSET_NPI-PROVIDER_NAME_PREFIX_TEXT].as_small_text AS Prefix, 
[BSET_NPI-PROVIDER_FIRST_NAME].as_small_text AS First_Name, 
[BSET_NPI-PROVIDER_MIDDLE_NAME].as_small_text AS Middle_Name, 
[BSET_NPI-PROVIDER_LAST_NAME_LEGAL_NAME].as_small_text AS Last_Name, 
[BSET_NPI-PROVIDER_NAME_SUFFIX_TEXT].as_small_text AS Suffix, 
[BSET_NPI-PROVIDER_CREDENTIAL_TEXT].as_small_text AS Credential_Text, 
[BSET_NPI-PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME].as_small_text AS Organization_Name, 
[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1].as_small_text AS Taxonomy, 
BVW_TAXONOMY.TYPE AS Taxonomy_Type, 
BVW_TAXONOMY.CLASSIFICATION AS Taxonomy_Class, 
BVW_TAXONOMY.SPECIALIZATION AS Taxonomy_Specialization, 
BVW_TAXONOMY.DEFINITION AS Taxonomy_Definition, 
BVW_TAXONOMY.NOTES AS Taxonomy_Notes, 
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME].as_small_text as City, 
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME].as_small_text AS State_Or_Province, 
substring([BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE].as_small_text,1,5) AS Postal_Code, 
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER].as_small_text AS Telephone_Number,
[BVW_LAT_LONG].Latitude,
[BVW_LAT_LONG].Longitude
FROM         [BSET_NPI-NPI] LEFT OUTER JOIN
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER] ON 
[BSET_NPI-NPI].object_key = [BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER].object_key LEFT OUTER JOIN
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE] ON 
[BSET_NPI-NPI].object_key = [BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE].object_key LEFT OUTER JOIN
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME] ON 
[BSET_NPI-NPI].object_key = [BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME].object_key LEFT OUTER JOIN
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME] ON 
[BSET_NPI-NPI].object_key = [BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME].object_key LEFT OUTER JOIN
[BSET_NPI-PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME] ON 
[BSET_NPI-NPI].object_key = [BSET_NPI-PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME].object_key LEFT OUTER JOIN
[BSET_NPI-PROVIDER_CREDENTIAL_TEXT] ON [BSET_NPI-NPI].object_key = [BSET_NPI-PROVIDER_CREDENTIAL_TEXT].object_key LEFT OUTER JOIN
[BSET_NPI-PROVIDER_NAME_SUFFIX_TEXT] ON [BSET_NPI-NPI].object_key = [BSET_NPI-PROVIDER_NAME_SUFFIX_TEXT].object_key LEFT OUTER JOIN
[BSET_NPI-PROVIDER_LAST_NAME_LEGAL_NAME] ON [BSET_NPI-NPI].object_key = [BSET_NPI-PROVIDER_LAST_NAME_LEGAL_NAME].object_key LEFT OUTER JOIN
[BSET_NPI-PROVIDER_MIDDLE_NAME] ON [BSET_NPI-NPI].object_key = [BSET_NPI-PROVIDER_MIDDLE_NAME].object_key LEFT OUTER JOIN
[BSET_NPI-PROVIDER_FIRST_NAME] ON [BSET_NPI-NPI].object_key = [BSET_NPI-PROVIDER_FIRST_NAME].object_key LEFT OUTER JOIN
[BSET_NPI-PROVIDER_NAME_PREFIX_TEXT] ON [BSET_NPI-NPI].object_key = [BSET_NPI-PROVIDER_NAME_PREFIX_TEXT].object_key LEFT OUTER JOIN
[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1] ON 
[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1].object_key = [BSET_NPI-NPI].object_key LEFT OUTER JOIN
BVW_TAXONOMY ON BVW_TAXONOMY.CODE = [BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1].as_small_text
left outer join [BVW_LAT_LONG] on
[BVW_LAT_LONG].object_key = [BSET_NPI-NPI].object_key



