create view BVWX_ENUMERATION_DATE_TAXONOMY
as
SELECT 
floor([BSET_NPI-PROVIDER_ENUMERATION_DATE].as_number/100000000) as Enumeration_YYYYMM, 
[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1].as_small_text as Taxonomy,
COUNT(*) as Cardinality
FROM         [BSET_NPI-PROVIDER_ENUMERATION_DATE] LEFT OUTER JOIN
[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1] ON 
[BSET_NPI-PROVIDER_ENUMERATION_DATE].object_key = 
[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1].object_key
group by 
floor([BSET_NPI-PROVIDER_ENUMERATION_DATE].as_number/100000000), 
[BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1].as_small_text