create view BVW_PROVIDER_BASIC_SEARCH
as
SELECT
[BSET_NPI-PROVIDER_CREDENTIAL_TEXT].as_small_text AS Provider_Credential, 
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME].as_small_text AS City, 
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME].as_small_text AS StateOrProvince, 
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE].as_small_text AS Postal_Code, 
[BSET_NPI-PROVIDER_GENDER_CODE].as_small_text as Gender, 
[BSET_NPI-PROVIDER_LAST_NAME_LEGAL_NAME].as_small_text As Last_Name,
COUNT(*) as Cardinality
FROM         [BSET_NPI-PROVIDER_CREDENTIAL_TEXT] LEFT OUTER JOIN
[BSET_NPI-PROVIDER_LAST_NAME_LEGAL_NAME] ON 
[BSET_NPI-PROVIDER_CREDENTIAL_TEXT].object_key = 
[BSET_NPI-PROVIDER_LAST_NAME_LEGAL_NAME].object_key LEFT OUTER JOIN
[BSET_NPI-PROVIDER_GENDER_CODE] ON 
[BSET_NPI-PROVIDER_CREDENTIAL_TEXT].object_key = 
[BSET_NPI-PROVIDER_GENDER_CODE].object_key LEFT OUTER JOIN
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME] ON 
[BSET_NPI-PROVIDER_CREDENTIAL_TEXT].object_key = 
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME].object_key LEFT OUTER
JOIN
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE] ON 
[BSET_NPI-PROVIDER_CREDENTIAL_TEXT].object_key = 
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE].object_key LEFT OUTER
JOIN
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME] ON 
[BSET_NPI-PROVIDER_CREDENTIAL_TEXT].object_key = 
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME].object_key
group by
[BSET_NPI-PROVIDER_CREDENTIAL_TEXT].as_small_text, 
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME].as_small_text, 
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME].as_small_text, 
[BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE].as_small_text, 
[BSET_NPI-PROVIDER_GENDER_CODE].as_small_text, 
[BSET_NPI-PROVIDER_LAST_NAME_LEGAL_NAME].as_small_text