create view [BVW_WIKI_LEAK-DIPLOMATIC]
as
SELECT     
	[BAL_WIKI_LEAK].dbo.[BSET_WIKI_DIPLOMATIC-LINE_NUMBER-INT].[key] as OBJECT_KEY, 
	[BAL_WIKI_LEAK].dbo.[BSET_WIKI_DIPLOMATIC-LINE_NUMBER-INT].val as [LINE_NUMBER-INT], 
	[BAL_WIKI_LEAK].dbo.[BSET_WIKI_DIPLOMATIC-FILE-TXTS].val AS [FILE-TXTS], 
    [BAL_WIKI_LEAK].dbo.[BSET_WIKI_DIPLOMATIC-LINE_CONTENT-TXTS].val AS [LINE_CONTENT-TXTS], 
    [BSET_WIKI_DIPLOMATIC-LINE_CONTENT-TXTL].val AS [LINE_CONTENT-TXTL]
FROM         
[BAL_WIKI_LEAK].dbo.[BSET_WIKI_DIPLOMATIC-LINE_NUMBER-INT] LEFT OUTER JOIN
[BAL_WIKI_LEAK].dbo.[BSET_WIKI_DIPLOMATIC-LINE_CONTENT-TXTL] ON 
[BAL_WIKI_LEAK].dbo.[BSET_WIKI_DIPLOMATIC-LINE_NUMBER-INT].[key] = 
[BAL_WIKI_LEAK].dbo.[BSET_WIKI_DIPLOMATIC-LINE_CONTENT-TXTL].[key] LEFT OUTER JOIN
[BAL_WIKI_LEAK].dbo.[BSET_WIKI_DIPLOMATIC-FILE-TXTS] ON 
[BAL_WIKI_LEAK].dbo.[BSET_WIKI_DIPLOMATIC-LINE_NUMBER-INT].[key] = 
[BAL_WIKI_LEAK].dbo.[BSET_WIKI_DIPLOMATIC-FILE-TXTS].[key] LEFT OUTER JOIN
[BAL_WIKI_LEAK].dbo.[BSET_WIKI_DIPLOMATIC-LINE_CONTENT-TXTS] ON 
[BAL_WIKI_LEAK].dbo.[BSET_WIKI_DIPLOMATIC-LINE_NUMBER-INT].[key] = 
[BAL_WIKI_LEAK].dbo.[BSET_WIKI_DIPLOMATIC-LINE_CONTENT-TXTS].[key]