USE [dndx_providers_2]

CREATE NONCLUSTERED INDEX [idx_npi_2] ON [dbo].[baltb_npi_2] 
(
	[NPI_PK] ASC,
	[PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME] ASC,
	[PROVIDER_LAST_NAME_LEGAL_NAME] ASC,
	[PROVIDER_FIRST_NAME] ASC,
	[PROVIDER_MIDDLE_NAME] ASC,
	[PROVIDER_NAME_PREFIX_TEXT] ASC,
	[PROVIDER_NAME_SUFFIX_TEXT] ASC,
	[PROVIDER_CREDENTIAL_TEXT] ASC,
	[PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS] ASC,
	[PROVIDER_SECOND_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS] ASC,
	[PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME] ASC,
	[PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME] ASC,
	[PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE] ASC,
	[PROVIDER_GENDER_CODE] ASC,
	[HEALTHCARE_PROVIDER_TAXONOMY_CODE_1] ASC,
	[HEALTHCARE_PROVIDER_TAXONOMY_CODE_2] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, 
SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, 
ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [idx_double] ON [dbo].[dim_double] 
(
	[dim_key] ASC,
	[dim_value] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [idx_integer] ON [dbo].[dim_integer] 
(
	[dim_key] ASC,
	[dim_value] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [idx_text] ON [dbo].[dim_text] 
(
	[dim_key] ASC,
	[dim_value] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [idx_time] ON [dbo].[dim_time] 
(
	[dim_key] ASC,
	[dim_value] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [idx_taxonomy] ON [dbo].[taxonomy_code] 
(
	[Code] ASC,
	[Type] ASC,
	[Classification] ASC,
	[Specialization] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]







