create view BVW_BSET_SHOW_WEB_META_2
as
SELECT     
	BVW_BSET_SHOW_WEB_META_1.DATABASE_NAME, 
	BVW_BSET_SHOW_WEB_META_1.OBJECT_NAME, 
	BVW_BSET_SHOW_WEB_META_1.TABLE_NAME, 
    max(BSET_LIST.TOTAL_CARDINALITY) as TOTAL_CARDINALITY
FROM         BVW_BSET_SHOW_WEB_META_1 
INNER JOIN
BSET_LIST on (BSET_LIST.DATABASE_NAME like '%' + BVW_BSET_SHOW_WEB_META_1.DATABASE_NAME + '%' 
AND 
BSET_LIST.OBJECT_NAME like '%' + BVW_BSET_SHOW_WEB_META_1.OBJECT_NAME + '%')
group by 	BVW_BSET_SHOW_WEB_META_1.DATABASE_NAME, 
	BVW_BSET_SHOW_WEB_META_1.OBJECT_NAME, 
	BVW_BSET_SHOW_WEB_META_1.TABLE_NAME