SELECT     TOP (100) [BSET_NPI-NPI].object_key, [BSET_NPI-NPI].as_number, 
                      [BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER].as_small_text, 
                      [BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE].as_small_text AS Expr1, 
                      [BSET_NPI-PROVIDER_LAST_NAME_LEGAL_NAME].as_small_text AS Expr2, [BSET_NPI-PROVIDER_NAME_PREFIX_TEXT].as_small_text AS Expr3, 
                      [BSET_NPI-PROVIDER_NAME_SUFFIX_TEXT].as_small_text AS Expr4, 
                      [BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME].as_small_text AS Expr5, 
                      [BSET_NPI-PROVIDER_GENDER_CODE].as_small_text AS Expr6, 
                      [BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME].as_small_text AS Expr7, 
                      [BSET_NPI-PROVIDER_FIRST_NAME].as_small_text AS Expr8, [BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1].as_small_text AS Expr9, 
                      [BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_2].as_small_text AS Expr10, [BSET_TAXONOMY-CLASSIFICATION].as_small_text AS Expr11, 
                      [BSET_TAXONOMY-CLASSIFICATION_2].as_small_text AS Expr12, [BSET_TAXONOMY-CLASSIFICATION_1].as_small_text AS Expr13, 
                      [BSET_TAXONOMY-SPECIALIZATION].as_small_text AS Expr14
FROM         [BSET_TAXONOMY-SPECIALIZATION] RIGHT OUTER JOIN
                      [BSET_TAXONOMY-CODE] AS [BSET_TAXONOMY-CODE_1] LEFT OUTER JOIN
                      [BSET_TAXONOMY-CLASSIFICATION] AS [BSET_TAXONOMY-CLASSIFICATION_2] ON 
                      [BSET_TAXONOMY-CODE_1].object_key = [BSET_TAXONOMY-CLASSIFICATION_2].object_key ON 
                      [BSET_TAXONOMY-SPECIALIZATION].object_key = [BSET_TAXONOMY-CODE_1].object_key RIGHT OUTER JOIN
                      [BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1] ON 
                      [BSET_TAXONOMY-CODE_1].as_small_text = [BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1].as_small_text RIGHT OUTER JOIN
                      [BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_2] LEFT OUTER JOIN
                      [BSET_TAXONOMY-CODE] LEFT OUTER JOIN
                      [BSET_TAXONOMY-CLASSIFICATION] AS [BSET_TAXONOMY-CLASSIFICATION_1] ON 
                      [BSET_TAXONOMY-CODE].object_key = [BSET_TAXONOMY-CLASSIFICATION_1].object_key LEFT OUTER JOIN
                      [BSET_TAXONOMY-CLASSIFICATION] ON [BSET_TAXONOMY-CODE].object_key = [BSET_TAXONOMY-CLASSIFICATION].object_key ON 
                      [BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_2].as_small_text = [BSET_TAXONOMY-CODE].as_small_text RIGHT OUTER JOIN
                      [BSET_NPI-NPI] ON [BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_2].object_key = [BSET_NPI-NPI].object_key ON 
                      [BSET_NPI-HEALTHCARE_PROVIDER_TAXONOMY_CODE_1].object_key = [BSET_NPI-NPI].object_key LEFT OUTER JOIN
                      [BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE] ON 
                      [BSET_NPI-NPI].object_key = [BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE].object_key LEFT OUTER JOIN
                      [BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER] ON 
                      [BSET_NPI-NPI].object_key = [BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER].object_key LEFT OUTER JOIN
                      [BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME] ON 
                      [BSET_NPI-NPI].object_key = [BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME].object_key LEFT OUTER JOIN
                      [BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME] ON 
                      [BSET_NPI-NPI].object_key = [BSET_NPI-PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME].object_key LEFT OUTER JOIN
                      [BSET_NPI-PROVIDER_FIRST_NAME] ON [BSET_NPI-NPI].object_key = [BSET_NPI-PROVIDER_FIRST_NAME].object_key LEFT OUTER JOIN
                      [BSET_NPI-PROVIDER_NAME_SUFFIX_TEXT] ON [BSET_NPI-NPI].object_key = [BSET_NPI-PROVIDER_NAME_SUFFIX_TEXT].object_key LEFT OUTER JOIN
                      [BSET_NPI-PROVIDER_LAST_NAME_LEGAL_NAME] ON [BSET_NPI-NPI].object_key = [BSET_NPI-PROVIDER_LAST_NAME_LEGAL_NAME].object_key LEFT OUTER JOIN
                      [BSET_NPI-PROVIDER_NAME_PREFIX_TEXT] ON [BSET_NPI-NPI].object_key = [BSET_NPI-PROVIDER_NAME_PREFIX_TEXT].object_key LEFT OUTER JOIN
                      [BSET_NPI-PROVIDER_GENDER_CODE] ON [BSET_NPI-NPI].object_key = [BSET_NPI-PROVIDER_GENDER_CODE].object_key