create procedure bproc_generate_meta_simple

as

IF EXISTS (
SELECT 1 FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'BSET_SIMPLE_META' AND TABLE_SCHEMA = 'DBO'
)
BEGIN
	DROP TABLE [BAL_VIEWS].[dbo].[BSET_SIMPLE_META];
END

select * 
into [BAL_VIEWS].[dbo].[BSET_SIMPLE_META]
from 
(
SELECT
getdate() as CREATED_ON,
'BAL_LOCATION' as DATABASE_NAME,
TABLE_NAME,
DATA_TYPE, 
PARSENAME(REPLACE(table_name, '-', '.'), 3) as OBJECT_NAME, 
PARSENAME(REPLACE(table_name, '-', '.'), 2) as PROPERTY_NAME,             
PARSENAME(REPLACE(table_name, '-', '.'), 1) as BALEEN_TYPE, 
CHARACTER_MAXIMUM_LENGTH,  
CHARACTER_OCTET_LENGTH,  
NUMERIC_PRECISION,  
CHARACTER_SET_NAME,  
COLLATION_NAME
FROM [BAL_LOCATION].information_schema.COLUMNS 
where COLUMN_NAME = 'val' and 
TABLE_NAME like 'BSET_%' 
union
SELECT
getdate() as CREATED_ON,
'BAL_MEDICAL_CODE_SETS' as DATABASE_NAME,
TABLE_NAME,
DATA_TYPE, 
PARSENAME(REPLACE(table_name, '-', '.'), 3) as OBJECT_NAME, 
PARSENAME(REPLACE(table_name, '-', '.'), 2) as PROPERTY_NAME,             
PARSENAME(REPLACE(table_name, '-', '.'), 1) as BALEEN_TYPE, 
CHARACTER_MAXIMUM_LENGTH,  
CHARACTER_OCTET_LENGTH,  
NUMERIC_PRECISION,  
CHARACTER_SET_NAME,  
COLLATION_NAME
FROM [BAL_MEDICAL_CODE_SETS].information_schema.COLUMNS 
where COLUMN_NAME = 'val' and 
TABLE_NAME like 'BSET_%' 
union
SELECT
getdate() as CREATED_ON,
'BAL_PROVIDER' as DATABASE_NAME,
TABLE_NAME,
DATA_TYPE, 
PARSENAME(REPLACE(table_name, '-', '.'), 3) as OBJECT_NAME, 
PARSENAME(REPLACE(table_name, '-', '.'), 2) as PROPERTY_NAME,             
PARSENAME(REPLACE(table_name, '-', '.'), 1) as BALEEN_TYPE, 
CHARACTER_MAXIMUM_LENGTH,  
CHARACTER_OCTET_LENGTH,  
NUMERIC_PRECISION,  
CHARACTER_SET_NAME,  
COLLATION_NAME
FROM [BAL_PROVIDER].information_schema.COLUMNS 
where COLUMN_NAME = 'val' and 
TABLE_NAME like 'BSET_%' 
union
SELECT
getdate() as CREATED_ON,
'BAL_WIKI_LEAK' as DATABASE_NAME,
TABLE_NAME,
DATA_TYPE, 
PARSENAME(REPLACE(table_name, '-', '.'), 3) as OBJECT_NAME, 
PARSENAME(REPLACE(table_name, '-', '.'), 2) as PROPERTY_NAME,             
PARSENAME(REPLACE(table_name, '-', '.'), 1) as BALEEN_TYPE, 
CHARACTER_MAXIMUM_LENGTH,  
CHARACTER_OCTET_LENGTH,  
NUMERIC_PRECISION,  
CHARACTER_SET_NAME,  
COLLATION_NAME
FROM [BAL_WIKI_LEAK].information_schema.COLUMNS 
where COLUMN_NAME = 'val' and 
TABLE_NAME like 'BSET_%' 
) t
order by t.OBJECT_NAME asc, t.PROPERTY_NAME asc